/// <reference path="./_helpers.d.ts" />
/// <reference path="./android.graphics.Matrix.d.ts" />
/// <reference path="./android.os.Parcel.d.ts" />
/// <reference path="./java.lang.Object.d.ts" />
/// <reference path="./java.lang.String.d.ts" />

declare module android {
	export module view {
		export class MotionEvent {
			public finalize(): void;
			public static obtain(param0: number, param1: number, param2: number, param3: number, param4: native.Array<android.view.MotionEvent.PointerProperties>, param5: native.Array<android.view.MotionEvent.PointerCoords>, param6: number, param7: number, param8: number, param9: number, param10: number, param11: number, param12: number, param13: number): android.view.MotionEvent;
			public static obtain(param0: number, param1: number, param2: number, param3: number, param4: native.Array<number>, param5: native.Array<android.view.MotionEvent.PointerCoords>, param6: number, param7: number, param8: number, param9: number, param10: number, param11: number, param12: number): android.view.MotionEvent;
			public static obtain(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: number, param9: number, param10: number, param11: number): android.view.MotionEvent;
			public static obtain(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: number, param9: number, param10: number, param11: number, param12: number): android.view.MotionEvent;
			public static obtain(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number): android.view.MotionEvent;
			public static obtain(param0: android.view.MotionEvent): android.view.MotionEvent;
			public static obtainNoHistory(param0: android.view.MotionEvent): android.view.MotionEvent;
			public recycle(): void;
			public getDeviceId(): number;
			public getSource(): number;
			public setSource(param0: number): void;
			public getAction(): number;
			public getActionMasked(): number;
			public getActionIndex(): number;
			public getFlags(): number;
			public getDownTime(): number;
			public getEventTime(): number;
			public getX(): number;
			public getY(): number;
			public getPressure(): number;
			public getSize(): number;
			public getTouchMajor(): number;
			public getTouchMinor(): number;
			public getToolMajor(): number;
			public getToolMinor(): number;
			public getOrientation(): number;
			public getAxisValue(param0: number): number;
			public getPointerCount(): number;
			public getPointerId(param0: number): number;
			public getToolType(param0: number): number;
			public findPointerIndex(param0: number): number;
			public getX(param0: number): number;
			public getY(param0: number): number;
			public getPressure(param0: number): number;
			public getSize(param0: number): number;
			public getTouchMajor(param0: number): number;
			public getTouchMinor(param0: number): number;
			public getToolMajor(param0: number): number;
			public getToolMinor(param0: number): number;
			public getOrientation(param0: number): number;
			public getAxisValue(param0: number, param1: number): number;
			public getPointerCoords(param0: number, param1: android.view.MotionEvent.PointerCoords): void;
			public getPointerProperties(param0: number, param1: android.view.MotionEvent.PointerProperties): void;
			public getMetaState(): number;
			public getButtonState(): number;
			public getActionButton(): number;
			public getRawX(): number;
			public getRawY(): number;
			public getXPrecision(): number;
			public getYPrecision(): number;
			public getHistorySize(): number;
			public getHistoricalEventTime(param0: number): number;
			public getHistoricalX(param0: number): number;
			public getHistoricalY(param0: number): number;
			public getHistoricalPressure(param0: number): number;
			public getHistoricalSize(param0: number): number;
			public getHistoricalTouchMajor(param0: number): number;
			public getHistoricalTouchMinor(param0: number): number;
			public getHistoricalToolMajor(param0: number): number;
			public getHistoricalToolMinor(param0: number): number;
			public getHistoricalOrientation(param0: number): number;
			public getHistoricalAxisValue(param0: number, param1: number): number;
			public getHistoricalX(param0: number, param1: number): number;
			public getHistoricalY(param0: number, param1: number): number;
			public getHistoricalPressure(param0: number, param1: number): number;
			public getHistoricalSize(param0: number, param1: number): number;
			public getHistoricalTouchMajor(param0: number, param1: number): number;
			public getHistoricalTouchMinor(param0: number, param1: number): number;
			public getHistoricalToolMajor(param0: number, param1: number): number;
			public getHistoricalToolMinor(param0: number, param1: number): number;
			public getHistoricalOrientation(param0: number, param1: number): number;
			public getHistoricalAxisValue(param0: number, param1: number, param2: number): number;
			public getHistoricalPointerCoords(param0: number, param1: number, param2: android.view.MotionEvent.PointerCoords): void;
			public getEdgeFlags(): number;
			public setEdgeFlags(param0: number): void;
			public setAction(param0: number): void;
			public offsetLocation(param0: number, param1: number): void;
			public setLocation(param0: number, param1: number): void;
			public transform(param0: android.graphics.Matrix): void;
			public addBatch(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number): void;
			public addBatch(param0: number, param1: native.Array<android.view.MotionEvent.PointerCoords>, param2: number): void;
			public toString(): string;
			public static actionToString(param0: number): string;
			public static axisToString(param0: number): string;
			public static axisFromString(param0: string): number;
			public isButtonPressed(param0: number): boolean;
			public writeToParcel(param0: android.os.Parcel, param1: number): void;
			public static ACTION_BUTTON_PRESS: number;
			public static ACTION_BUTTON_RELEASE: number;
			public static ACTION_CANCEL: number;
			public static ACTION_DOWN: number;
			public static ACTION_HOVER_ENTER: number;
			public static ACTION_HOVER_EXIT: number;
			public static ACTION_HOVER_MOVE: number;
			public static ACTION_MASK: number;
			public static ACTION_MOVE: number;
			public static ACTION_OUTSIDE: number;
			public static ACTION_POINTER_1_DOWN: number;
			public static ACTION_POINTER_1_UP: number;
			public static ACTION_POINTER_2_DOWN: number;
			public static ACTION_POINTER_2_UP: number;
			public static ACTION_POINTER_3_DOWN: number;
			public static ACTION_POINTER_3_UP: number;
			public static ACTION_POINTER_DOWN: number;
			public static ACTION_POINTER_ID_MASK: number;
			public static ACTION_POINTER_ID_SHIFT: number;
			public static ACTION_POINTER_INDEX_MASK: number;
			public static ACTION_POINTER_INDEX_SHIFT: number;
			public static ACTION_POINTER_UP: number;
			public static ACTION_SCROLL: number;
			public static ACTION_UP: number;
			public static AXIS_BRAKE: number;
			public static AXIS_DISTANCE: number;
			public static AXIS_GAS: number;
			public static AXIS_GENERIC_1: number;
			public static AXIS_GENERIC_10: number;
			public static AXIS_GENERIC_11: number;
			public static AXIS_GENERIC_12: number;
			public static AXIS_GENERIC_13: number;
			public static AXIS_GENERIC_14: number;
			public static AXIS_GENERIC_15: number;
			public static AXIS_GENERIC_16: number;
			public static AXIS_GENERIC_2: number;
			public static AXIS_GENERIC_3: number;
			public static AXIS_GENERIC_4: number;
			public static AXIS_GENERIC_5: number;
			public static AXIS_GENERIC_6: number;
			public static AXIS_GENERIC_7: number;
			public static AXIS_GENERIC_8: number;
			public static AXIS_GENERIC_9: number;
			public static AXIS_HAT_X: number;
			public static AXIS_HAT_Y: number;
			public static AXIS_HSCROLL: number;
			public static AXIS_LTRIGGER: number;
			public static AXIS_ORIENTATION: number;
			public static AXIS_PRESSURE: number;
			public static AXIS_RTRIGGER: number;
			public static AXIS_RUDDER: number;
			public static AXIS_RX: number;
			public static AXIS_RY: number;
			public static AXIS_RZ: number;
			public static AXIS_SIZE: number;
			public static AXIS_THROTTLE: number;
			public static AXIS_TILT: number;
			public static AXIS_TOOL_MAJOR: number;
			public static AXIS_TOOL_MINOR: number;
			public static AXIS_TOUCH_MAJOR: number;
			public static AXIS_TOUCH_MINOR: number;
			public static AXIS_VSCROLL: number;
			public static AXIS_WHEEL: number;
			public static AXIS_X: number;
			public static AXIS_Y: number;
			public static AXIS_Z: number;
			public static BUTTON_BACK: number;
			public static BUTTON_FORWARD: number;
			public static BUTTON_PRIMARY: number;
			public static BUTTON_SECONDARY: number;
			public static BUTTON_STYLUS_PRIMARY: number;
			public static BUTTON_STYLUS_SECONDARY: number;
			public static BUTTON_TERTIARY: number;
			public static CREATOR: android.os.Parcelable.Creator;
			public static EDGE_BOTTOM: number;
			public static EDGE_LEFT: number;
			public static EDGE_RIGHT: number;
			public static EDGE_TOP: number;
			public static FLAG_WINDOW_IS_OBSCURED: number;
			public static INVALID_POINTER_ID: number;
			public static TOOL_TYPE_ERASER: number;
			public static TOOL_TYPE_FINGER: number;
			public static TOOL_TYPE_MOUSE: number;
			public static TOOL_TYPE_STYLUS: number;
			public static TOOL_TYPE_UNKNOWN: number;
		}
		export module MotionEvent {
			export class PointerCoords {
				public constructor();
				public constructor(param0: android.view.MotionEvent.PointerCoords);
				public clear(): void;
				public copyFrom(param0: android.view.MotionEvent.PointerCoords): void;
				public getAxisValue(param0: number): number;
				public setAxisValue(param0: number, param1: number): void;
				public orientation: number;
				public pressure: number;
				public size: number;
				public toolMajor: number;
				public toolMinor: number;
				public touchMajor: number;
				public touchMinor: number;
				public x: number;
				public y: number;
			}
			export class PointerProperties {
				public constructor();
				public constructor(param0: android.view.MotionEvent.PointerProperties);
				public clear(): void;
				public copyFrom(param0: android.view.MotionEvent.PointerProperties): void;
				public equals(param0: java.lang.Object): boolean;
				public hashCode(): number;
				public id: number;
				public toolType: number;
			}
		}
	}
}
