/// <reference path="./_helpers.d.ts" />
/// <reference path="./android.graphics.Rect.d.ts" />
/// <reference path="./android.os.Bundle.d.ts" />
/// <reference path="./android.support.v4.view.accessibility.AccessibilityWindowInfoCompat.d.ts" />
/// <reference path="./android.view.View.d.ts" />
/// <reference path="./java.lang.CharSequence.d.ts" />
/// <reference path="./java.lang.Object.d.ts" />
/// <reference path="./java.lang.String.d.ts" />
/// <reference path="./java.util.List.d.ts" />

declare module android {
	export module support {
		export module v4 {
			export module view {
				export module accessibility {
					export class AccessibilityNodeInfoCompat {
						public constructor();
						public constructor(param0: java.lang.Object);
						public getInfo(): java.lang.Object;
						public static obtain(param0: android.view.View): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
						public static obtain(param0: android.view.View, param1: number): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
						public static obtain(): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
						public static obtain(param0: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
						public setSource(param0: android.view.View): void;
						public setSource(param0: android.view.View, param1: number): void;
						public findFocus(param0: number): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
						public focusSearch(param0: number): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
						public getWindowId(): number;
						public getChildCount(): number;
						public getChild(param0: number): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
						public addChild(param0: android.view.View): void;
						public addChild(param0: android.view.View, param1: number): void;
						public removeChild(param0: android.view.View): boolean;
						public removeChild(param0: android.view.View, param1: number): boolean;
						public getActions(): number;
						public addAction(param0: number): void;
						public addAction(param0: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat): void;
						public removeAction(param0: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat): boolean;
						public performAction(param0: number): boolean;
						public performAction(param0: number, param1: android.os.Bundle): boolean;
						public setMovementGranularities(param0: number): void;
						public getMovementGranularities(): number;
						public findAccessibilityNodeInfosByText(param0: string): java.util.List;
						public getParent(): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
						public setParent(param0: android.view.View): void;
						public setParent(param0: android.view.View, param1: number): void;
						public getBoundsInParent(param0: android.graphics.Rect): void;
						public setBoundsInParent(param0: android.graphics.Rect): void;
						public getBoundsInScreen(param0: android.graphics.Rect): void;
						public setBoundsInScreen(param0: android.graphics.Rect): void;
						public isCheckable(): boolean;
						public setCheckable(param0: boolean): void;
						public isChecked(): boolean;
						public setChecked(param0: boolean): void;
						public isFocusable(): boolean;
						public setFocusable(param0: boolean): void;
						public isFocused(): boolean;
						public setFocused(param0: boolean): void;
						public isVisibleToUser(): boolean;
						public setVisibleToUser(param0: boolean): void;
						public isAccessibilityFocused(): boolean;
						public setAccessibilityFocused(param0: boolean): void;
						public isSelected(): boolean;
						public setSelected(param0: boolean): void;
						public isClickable(): boolean;
						public setClickable(param0: boolean): void;
						public isLongClickable(): boolean;
						public setLongClickable(param0: boolean): void;
						public isEnabled(): boolean;
						public setEnabled(param0: boolean): void;
						public isPassword(): boolean;
						public setPassword(param0: boolean): void;
						public isScrollable(): boolean;
						public setScrollable(param0: boolean): void;
						public getPackageName(): string;
						public setPackageName(param0: string): void;
						public getClassName(): string;
						public setClassName(param0: string): void;
						public getText(): string;
						public setText(param0: string): void;
						public getContentDescription(): string;
						public setContentDescription(param0: string): void;
						public recycle(): void;
						public setViewIdResourceName(param0: string): void;
						public getViewIdResourceName(): string;
						public getLiveRegion(): number;
						public setLiveRegion(param0: number): void;
						public getCollectionInfo(): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.CollectionInfoCompat;
						public setCollectionInfo(param0: java.lang.Object): void;
						public setCollectionItemInfo(param0: java.lang.Object): void;
						public getCollectionItemInfo(): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.CollectionItemInfoCompat;
						public getRangeInfo(): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.RangeInfoCompat;
						public setRangeInfo(param0: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.RangeInfoCompat): void;
						public getActionList(): java.util.List;
						public setContentInvalid(param0: boolean): void;
						public isContentInvalid(): boolean;
						public setError(param0: string): void;
						public getError(): string;
						public setLabelFor(param0: android.view.View): void;
						public setLabelFor(param0: android.view.View, param1: number): void;
						public getLabelFor(): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
						public setLabeledBy(param0: android.view.View): void;
						public setLabeledBy(param0: android.view.View, param1: number): void;
						public getLabeledBy(): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
						public canOpenPopup(): boolean;
						public setCanOpenPopup(param0: boolean): void;
						public findAccessibilityNodeInfosByViewId(param0: string): java.util.List;
						public getExtras(): android.os.Bundle;
						public getInputType(): number;
						public setInputType(param0: number): void;
						public setMaxTextLength(param0: number): void;
						public getMaxTextLength(): number;
						public setTextSelection(param0: number, param1: number): void;
						public getTextSelectionStart(): number;
						public getTextSelectionEnd(): number;
						public getTraversalBefore(): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
						public setTraversalBefore(param0: android.view.View): void;
						public setTraversalBefore(param0: android.view.View, param1: number): void;
						public getTraversalAfter(): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
						public setTraversalAfter(param0: android.view.View): void;
						public setTraversalAfter(param0: android.view.View, param1: number): void;
						public getWindow(): android.support.v4.view.accessibility.AccessibilityWindowInfoCompat;
						public isDismissable(): boolean;
						public setDismissable(param0: boolean): void;
						public isEditable(): boolean;
						public setEditable(param0: boolean): void;
						public isMultiLine(): boolean;
						public setMultiLine(param0: boolean): void;
						public refresh(): boolean;
						public hashCode(): number;
						public equals(param0: java.lang.Object): boolean;
						public toString(): string;
						public static ACTION_FOCUS: number;
						public static ACTION_CLEAR_FOCUS: number;
						public static ACTION_SELECT: number;
						public static ACTION_CLEAR_SELECTION: number;
						public static ACTION_CLICK: number;
						public static ACTION_LONG_CLICK: number;
						public static ACTION_ACCESSIBILITY_FOCUS: number;
						public static ACTION_CLEAR_ACCESSIBILITY_FOCUS: number;
						public static ACTION_NEXT_AT_MOVEMENT_GRANULARITY: number;
						public static ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY: number;
						public static ACTION_NEXT_HTML_ELEMENT: number;
						public static ACTION_PREVIOUS_HTML_ELEMENT: number;
						public static ACTION_SCROLL_FORWARD: number;
						public static ACTION_SCROLL_BACKWARD: number;
						public static ACTION_COPY: number;
						public static ACTION_PASTE: number;
						public static ACTION_CUT: number;
						public static ACTION_SET_SELECTION: number;
						public static ACTION_EXPAND: number;
						public static ACTION_COLLAPSE: number;
						public static ACTION_DISMISS: number;
						public static ACTION_SET_TEXT: number;
						public static ACTION_ARGUMENT_MOVEMENT_GRANULARITY_INT: string;
						public static ACTION_ARGUMENT_HTML_ELEMENT_STRING: string;
						public static ACTION_ARGUMENT_EXTEND_SELECTION_BOOLEAN: string;
						public static ACTION_ARGUMENT_SELECTION_START_INT: string;
						public static ACTION_ARGUMENT_SELECTION_END_INT: string;
						public static ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE: string;
						public static FOCUS_INPUT: number;
						public static FOCUS_ACCESSIBILITY: number;
						public static MOVEMENT_GRANULARITY_CHARACTER: number;
						public static MOVEMENT_GRANULARITY_WORD: number;
						public static MOVEMENT_GRANULARITY_LINE: number;
						public static MOVEMENT_GRANULARITY_PARAGRAPH: number;
						public static MOVEMENT_GRANULARITY_PAGE: number;
					}
					export module AccessibilityNodeInfoCompat {
						export class AccessibilityActionCompat {
							public constructor();
							public constructor(param0: number, param1: string);
							public getId(): number;
							public getLabel(): string;
							public static ACTION_FOCUS: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_CLEAR_FOCUS: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_SELECT: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_CLEAR_SELECTION: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_CLICK: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_LONG_CLICK: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_ACCESSIBILITY_FOCUS: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_CLEAR_ACCESSIBILITY_FOCUS: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_NEXT_AT_MOVEMENT_GRANULARITY: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_NEXT_HTML_ELEMENT: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_PREVIOUS_HTML_ELEMENT: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_SCROLL_FORWARD: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_SCROLL_BACKWARD: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_COPY: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_PASTE: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_CUT: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_SET_SELECTION: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_EXPAND: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_COLLAPSE: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_DISMISS: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
							public static ACTION_SET_TEXT: android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
						}
						export class AccessibilityNodeInfoApi21Impl {
							public newAccessibilityAction(param0: number, param1: string): java.lang.Object;
							public getActionList(param0: java.lang.Object): java.util.List;
							public obtainCollectionInfo(param0: number, param1: number, param2: boolean, param3: number): java.lang.Object;
							public addAction(param0: java.lang.Object, param1: number): void;
							public addAction(param0: java.lang.Object, param1: java.lang.Object): void;
							public removeAction(param0: java.lang.Object, param1: java.lang.Object): boolean;
							public getAccessibilityActionId(param0: java.lang.Object): number;
							public getAccessibilityActionLabel(param0: java.lang.Object): string;
							public obtainCollectionItemInfo(param0: number, param1: number, param2: number, param3: number, param4: boolean, param5: boolean): java.lang.Object;
							public isCollectionItemSelected(param0: java.lang.Object): boolean;
							public getError(param0: java.lang.Object): string;
							public setError(param0: java.lang.Object, param1: string): void;
							public setMaxTextLength(param0: java.lang.Object, param1: number): void;
							public getMaxTextLength(param0: java.lang.Object): number;
							public getWindow(param0: java.lang.Object): java.lang.Object;
							public removeChild(param0: java.lang.Object, param1: android.view.View, param2: number): boolean;
							public removeChild(param0: java.lang.Object, param1: android.view.View): boolean;
							public removeChild(param0: java.lang.Object, param1: android.view.View, param2: number): boolean;
						}
						export class AccessibilityNodeInfoApi22Impl {
							public getTraversalBefore(param0: java.lang.Object): java.lang.Object;
							public setTraversalBefore(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public setTraversalBefore(param0: java.lang.Object, param1: android.view.View): void;
							public setTraversalBefore(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public getTraversalAfter(param0: java.lang.Object): java.lang.Object;
							public setTraversalAfter(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public setTraversalAfter(param0: java.lang.Object, param1: android.view.View): void;
							public setTraversalAfter(param0: java.lang.Object, param1: android.view.View, param2: number): void;
						}
						export class AccessibilityNodeInfoIcsImpl {
							public obtain(param0: android.view.View): java.lang.Object;
							public obtain(param0: android.view.View, param1: number): java.lang.Object;
							public obtain(param0: java.lang.Object): java.lang.Object;
							public obtain(): java.lang.Object;
							public obtain(param0: android.view.View): java.lang.Object;
							public obtain(param0: java.lang.Object): java.lang.Object;
							public addAction(param0: java.lang.Object, param1: java.lang.Object): void;
							public addAction(param0: java.lang.Object, param1: number): void;
							public addChild(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public addChild(param0: java.lang.Object, param1: android.view.View): void;
							public findAccessibilityNodeInfosByText(param0: java.lang.Object, param1: string): java.util.List;
							public getActions(param0: java.lang.Object): number;
							public getBoundsInParent(param0: java.lang.Object, param1: android.graphics.Rect): void;
							public getBoundsInScreen(param0: java.lang.Object, param1: android.graphics.Rect): void;
							public getChild(param0: java.lang.Object, param1: number): java.lang.Object;
							public getChildCount(param0: java.lang.Object): number;
							public getClassName(param0: java.lang.Object): string;
							public getContentDescription(param0: java.lang.Object): string;
							public getPackageName(param0: java.lang.Object): string;
							public getParent(param0: java.lang.Object): java.lang.Object;
							public getText(param0: java.lang.Object): string;
							public getWindowId(param0: java.lang.Object): number;
							public isCheckable(param0: java.lang.Object): boolean;
							public isChecked(param0: java.lang.Object): boolean;
							public isClickable(param0: java.lang.Object): boolean;
							public isEnabled(param0: java.lang.Object): boolean;
							public isFocusable(param0: java.lang.Object): boolean;
							public isFocused(param0: java.lang.Object): boolean;
							public isLongClickable(param0: java.lang.Object): boolean;
							public isPassword(param0: java.lang.Object): boolean;
							public isScrollable(param0: java.lang.Object): boolean;
							public isSelected(param0: java.lang.Object): boolean;
							public performAction(param0: java.lang.Object, param1: number, param2: android.os.Bundle): boolean;
							public performAction(param0: java.lang.Object, param1: number): boolean;
							public setBoundsInParent(param0: java.lang.Object, param1: android.graphics.Rect): void;
							public setBoundsInScreen(param0: java.lang.Object, param1: android.graphics.Rect): void;
							public setCheckable(param0: java.lang.Object, param1: boolean): void;
							public setChecked(param0: java.lang.Object, param1: boolean): void;
							public setClassName(param0: java.lang.Object, param1: string): void;
							public setClickable(param0: java.lang.Object, param1: boolean): void;
							public setContentDescription(param0: java.lang.Object, param1: string): void;
							public setEnabled(param0: java.lang.Object, param1: boolean): void;
							public setFocusable(param0: java.lang.Object, param1: boolean): void;
							public setFocused(param0: java.lang.Object, param1: boolean): void;
							public setLongClickable(param0: java.lang.Object, param1: boolean): void;
							public setPackageName(param0: java.lang.Object, param1: string): void;
							public setParent(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public setParent(param0: java.lang.Object, param1: android.view.View): void;
							public setPassword(param0: java.lang.Object, param1: boolean): void;
							public setScrollable(param0: java.lang.Object, param1: boolean): void;
							public setSelected(param0: java.lang.Object, param1: boolean): void;
							public setSource(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public setSource(param0: java.lang.Object, param1: android.view.View): void;
							public setText(param0: java.lang.Object, param1: string): void;
							public recycle(param0: java.lang.Object): void;
						}
						export class AccessibilityNodeInfoImpl {
							public newAccessibilityAction(param0: number, param1: string): java.lang.Object;
							public obtain(): java.lang.Object;
							public obtain(param0: android.view.View): java.lang.Object;
							public obtain(param0: java.lang.Object): java.lang.Object;
							public obtain(param0: android.view.View, param1: number): java.lang.Object;
							public setSource(param0: java.lang.Object, param1: android.view.View): void;
							public setSource(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public findFocus(param0: java.lang.Object, param1: number): java.lang.Object;
							public focusSearch(param0: java.lang.Object, param1: number): java.lang.Object;
							public getWindowId(param0: java.lang.Object): number;
							public getChildCount(param0: java.lang.Object): number;
							public getChild(param0: java.lang.Object, param1: number): java.lang.Object;
							public addChild(param0: java.lang.Object, param1: android.view.View): void;
							public addChild(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public removeChild(param0: java.lang.Object, param1: android.view.View): boolean;
							public removeChild(param0: java.lang.Object, param1: android.view.View, param2: number): boolean;
							public getActions(param0: java.lang.Object): number;
							public addAction(param0: java.lang.Object, param1: number): void;
							public addAction(param0: java.lang.Object, param1: java.lang.Object): void;
							public removeAction(param0: java.lang.Object, param1: java.lang.Object): boolean;
							public getAccessibilityActionId(param0: java.lang.Object): number;
							public getAccessibilityActionLabel(param0: java.lang.Object): string;
							public performAction(param0: java.lang.Object, param1: number): boolean;
							public performAction(param0: java.lang.Object, param1: number, param2: android.os.Bundle): boolean;
							public setMovementGranularities(param0: java.lang.Object, param1: number): void;
							public getMovementGranularities(param0: java.lang.Object): number;
							public findAccessibilityNodeInfosByText(param0: java.lang.Object, param1: string): java.util.List;
							public getParent(param0: java.lang.Object): java.lang.Object;
							public setParent(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public setParent(param0: java.lang.Object, param1: android.view.View): void;
							public getBoundsInParent(param0: java.lang.Object, param1: android.graphics.Rect): void;
							public setBoundsInParent(param0: java.lang.Object, param1: android.graphics.Rect): void;
							public getBoundsInScreen(param0: java.lang.Object, param1: android.graphics.Rect): void;
							public setBoundsInScreen(param0: java.lang.Object, param1: android.graphics.Rect): void;
							public isCheckable(param0: java.lang.Object): boolean;
							public setCheckable(param0: java.lang.Object, param1: boolean): void;
							public isChecked(param0: java.lang.Object): boolean;
							public setChecked(param0: java.lang.Object, param1: boolean): void;
							public isFocusable(param0: java.lang.Object): boolean;
							public setFocusable(param0: java.lang.Object, param1: boolean): void;
							public isFocused(param0: java.lang.Object): boolean;
							public setFocused(param0: java.lang.Object, param1: boolean): void;
							public isVisibleToUser(param0: java.lang.Object): boolean;
							public setVisibleToUser(param0: java.lang.Object, param1: boolean): void;
							public isAccessibilityFocused(param0: java.lang.Object): boolean;
							public setAccessibilityFocused(param0: java.lang.Object, param1: boolean): void;
							public isSelected(param0: java.lang.Object): boolean;
							public setSelected(param0: java.lang.Object, param1: boolean): void;
							public isClickable(param0: java.lang.Object): boolean;
							public setClickable(param0: java.lang.Object, param1: boolean): void;
							public isLongClickable(param0: java.lang.Object): boolean;
							public setLongClickable(param0: java.lang.Object, param1: boolean): void;
							public isEnabled(param0: java.lang.Object): boolean;
							public setEnabled(param0: java.lang.Object, param1: boolean): void;
							public isPassword(param0: java.lang.Object): boolean;
							public setPassword(param0: java.lang.Object, param1: boolean): void;
							public isScrollable(param0: java.lang.Object): boolean;
							public setScrollable(param0: java.lang.Object, param1: boolean): void;
							public getPackageName(param0: java.lang.Object): string;
							public setPackageName(param0: java.lang.Object, param1: string): void;
							public getClassName(param0: java.lang.Object): string;
							public setClassName(param0: java.lang.Object, param1: string): void;
							public getText(param0: java.lang.Object): string;
							public setText(param0: java.lang.Object, param1: string): void;
							public getContentDescription(param0: java.lang.Object): string;
							public setContentDescription(param0: java.lang.Object, param1: string): void;
							public recycle(param0: java.lang.Object): void;
							public getViewIdResourceName(param0: java.lang.Object): string;
							public setViewIdResourceName(param0: java.lang.Object, param1: string): void;
							public getLiveRegion(param0: java.lang.Object): number;
							public setLiveRegion(param0: java.lang.Object, param1: number): void;
							public getCollectionInfo(param0: java.lang.Object): java.lang.Object;
							public setCollectionInfo(param0: java.lang.Object, param1: java.lang.Object): void;
							public getCollectionItemInfo(param0: java.lang.Object): java.lang.Object;
							public setCollectionItemInfo(param0: java.lang.Object, param1: java.lang.Object): void;
							public getRangeInfo(param0: java.lang.Object): java.lang.Object;
							public setRangeInfo(param0: java.lang.Object, param1: java.lang.Object): void;
							public getActionList(param0: java.lang.Object): java.util.List;
							public obtainCollectionInfo(param0: number, param1: number, param2: boolean, param3: number): java.lang.Object;
							public getCollectionInfoColumnCount(param0: java.lang.Object): number;
							public getCollectionInfoRowCount(param0: java.lang.Object): number;
							public isCollectionInfoHierarchical(param0: java.lang.Object): boolean;
							public obtainCollectionItemInfo(param0: number, param1: number, param2: number, param3: number, param4: boolean, param5: boolean): java.lang.Object;
							public getCollectionItemColumnIndex(param0: java.lang.Object): number;
							public getCollectionItemColumnSpan(param0: java.lang.Object): number;
							public getCollectionItemRowIndex(param0: java.lang.Object): number;
							public getCollectionItemRowSpan(param0: java.lang.Object): number;
							public isCollectionItemHeading(param0: java.lang.Object): boolean;
							public isCollectionItemSelected(param0: java.lang.Object): boolean;
							public getTraversalBefore(param0: java.lang.Object): java.lang.Object;
							public setTraversalBefore(param0: java.lang.Object, param1: android.view.View): void;
							public setTraversalBefore(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public getTraversalAfter(param0: java.lang.Object): java.lang.Object;
							public setTraversalAfter(param0: java.lang.Object, param1: android.view.View): void;
							public setTraversalAfter(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public setContentInvalid(param0: java.lang.Object, param1: boolean): void;
							public isContentInvalid(param0: java.lang.Object): boolean;
							public setError(param0: java.lang.Object, param1: string): void;
							public getError(param0: java.lang.Object): string;
							public setLabelFor(param0: java.lang.Object, param1: android.view.View): void;
							public setLabelFor(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public getLabelFor(param0: java.lang.Object): java.lang.Object;
							public setLabeledBy(param0: java.lang.Object, param1: android.view.View): void;
							public setLabeledBy(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public getLabeledBy(param0: java.lang.Object): java.lang.Object;
							public canOpenPopup(param0: java.lang.Object): boolean;
							public setCanOpenPopup(param0: java.lang.Object, param1: boolean): void;
							public findAccessibilityNodeInfosByViewId(param0: java.lang.Object, param1: string): java.util.List;
							public getExtras(param0: java.lang.Object): android.os.Bundle;
							public getInputType(param0: java.lang.Object): number;
							public setInputType(param0: java.lang.Object, param1: number): void;
							public setMaxTextLength(param0: java.lang.Object, param1: number): void;
							public getMaxTextLength(param0: java.lang.Object): number;
							public setTextSelection(param0: java.lang.Object, param1: number, param2: number): void;
							public getTextSelectionStart(param0: java.lang.Object): number;
							public getTextSelectionEnd(param0: java.lang.Object): number;
							public getWindow(param0: java.lang.Object): java.lang.Object;
							public isDismissable(param0: java.lang.Object): boolean;
							public setDismissable(param0: java.lang.Object, param1: boolean): void;
							public isEditable(param0: java.lang.Object): boolean;
							public setEditable(param0: java.lang.Object, param1: boolean): void;
							public isMultiLine(param0: java.lang.Object): boolean;
							public setMultiLine(param0: java.lang.Object, param1: boolean): void;
							public refresh(param0: java.lang.Object): boolean;
						}
						export class AccessibilityNodeInfoJellybeanImpl {
							public obtain(): java.lang.Object;
							public obtain(param0: android.view.View): java.lang.Object;
							public obtain(param0: java.lang.Object): java.lang.Object;
							public obtain(param0: android.view.View, param1: number): java.lang.Object;
							public findFocus(param0: java.lang.Object, param1: number): java.lang.Object;
							public focusSearch(param0: java.lang.Object, param1: number): java.lang.Object;
							public addChild(param0: java.lang.Object, param1: android.view.View): void;
							public addChild(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public setSource(param0: java.lang.Object, param1: android.view.View): void;
							public setSource(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public isVisibleToUser(param0: java.lang.Object): boolean;
							public setVisibleToUser(param0: java.lang.Object, param1: boolean): void;
							public isAccessibilityFocused(param0: java.lang.Object): boolean;
							public setAccessibilityFocused(param0: java.lang.Object, param1: boolean): void;
							public performAction(param0: java.lang.Object, param1: number): boolean;
							public performAction(param0: java.lang.Object, param1: number, param2: android.os.Bundle): boolean;
							public setMovementGranularities(param0: java.lang.Object, param1: number): void;
							public getMovementGranularities(param0: java.lang.Object): number;
							public setParent(param0: java.lang.Object, param1: android.view.View): void;
							public setParent(param0: java.lang.Object, param1: android.view.View, param2: number): void;
						}
						export class AccessibilityNodeInfoJellybeanMr1Impl {
							public setLabelFor(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public setLabelFor(param0: java.lang.Object, param1: android.view.View): void;
							public setLabelFor(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public getLabelFor(param0: java.lang.Object): java.lang.Object;
							public setLabeledBy(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public setLabeledBy(param0: java.lang.Object, param1: android.view.View): void;
							public setLabeledBy(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public getLabeledBy(param0: java.lang.Object): java.lang.Object;
						}
						export class AccessibilityNodeInfoJellybeanMr2Impl {
							public getViewIdResourceName(param0: java.lang.Object): string;
							public setViewIdResourceName(param0: java.lang.Object, param1: string): void;
							public findAccessibilityNodeInfosByViewId(param0: java.lang.Object, param1: string): java.util.List;
							public setTextSelection(param0: java.lang.Object, param1: number, param2: number): void;
							public getTextSelectionStart(param0: java.lang.Object): number;
							public getTextSelectionEnd(param0: java.lang.Object): number;
							public isEditable(param0: java.lang.Object): boolean;
							public setEditable(param0: java.lang.Object, param1: boolean): void;
							public refresh(param0: java.lang.Object): boolean;
						}
						export class AccessibilityNodeInfoKitKatImpl {
							public getLiveRegion(param0: java.lang.Object): number;
							public setLiveRegion(param0: java.lang.Object, param1: number): void;
							public getCollectionInfo(param0: java.lang.Object): java.lang.Object;
							public setCollectionInfo(param0: java.lang.Object, param1: java.lang.Object): void;
							public obtainCollectionInfo(param0: number, param1: number, param2: boolean, param3: number): java.lang.Object;
							public obtainCollectionItemInfo(param0: number, param1: number, param2: number, param3: number, param4: boolean, param5: boolean): java.lang.Object;
							public getCollectionInfoColumnCount(param0: java.lang.Object): number;
							public getCollectionInfoRowCount(param0: java.lang.Object): number;
							public isCollectionInfoHierarchical(param0: java.lang.Object): boolean;
							public getCollectionItemInfo(param0: java.lang.Object): java.lang.Object;
							public getRangeInfo(param0: java.lang.Object): java.lang.Object;
							public setRangeInfo(param0: java.lang.Object, param1: java.lang.Object): void;
							public getCollectionItemColumnIndex(param0: java.lang.Object): number;
							public getCollectionItemColumnSpan(param0: java.lang.Object): number;
							public getCollectionItemRowIndex(param0: java.lang.Object): number;
							public getCollectionItemRowSpan(param0: java.lang.Object): number;
							public isCollectionItemHeading(param0: java.lang.Object): boolean;
							public setCollectionItemInfo(param0: java.lang.Object, param1: java.lang.Object): void;
							public setContentInvalid(param0: java.lang.Object, param1: boolean): void;
							public isContentInvalid(param0: java.lang.Object): boolean;
							public canOpenPopup(param0: java.lang.Object): boolean;
							public setCanOpenPopup(param0: java.lang.Object, param1: boolean): void;
							public getExtras(param0: java.lang.Object): android.os.Bundle;
							public getInputType(param0: java.lang.Object): number;
							public setInputType(param0: java.lang.Object, param1: number): void;
							public isDismissable(param0: java.lang.Object): boolean;
							public setDismissable(param0: java.lang.Object, param1: boolean): void;
							public isMultiLine(param0: java.lang.Object): boolean;
							public setMultiLine(param0: java.lang.Object, param1: boolean): void;
						}
						export class AccessibilityNodeInfoStubImpl {
							public newAccessibilityAction(param0: number, param1: string): java.lang.Object;
							public obtain(): java.lang.Object;
							public obtain(param0: android.view.View): java.lang.Object;
							public obtain(param0: android.view.View, param1: number): java.lang.Object;
							public obtain(param0: java.lang.Object): java.lang.Object;
							public addAction(param0: java.lang.Object, param1: number): void;
							public addAction(param0: java.lang.Object, param1: java.lang.Object): void;
							public removeAction(param0: java.lang.Object, param1: java.lang.Object): boolean;
							public getAccessibilityActionId(param0: java.lang.Object): number;
							public getAccessibilityActionLabel(param0: java.lang.Object): string;
							public addChild(param0: java.lang.Object, param1: android.view.View): void;
							public addChild(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public removeChild(param0: java.lang.Object, param1: android.view.View): boolean;
							public removeChild(param0: java.lang.Object, param1: android.view.View, param2: number): boolean;
							public findAccessibilityNodeInfosByText(param0: java.lang.Object, param1: string): java.util.List;
							public getActions(param0: java.lang.Object): number;
							public getBoundsInParent(param0: java.lang.Object, param1: android.graphics.Rect): void;
							public getBoundsInScreen(param0: java.lang.Object, param1: android.graphics.Rect): void;
							public getChild(param0: java.lang.Object, param1: number): java.lang.Object;
							public getChildCount(param0: java.lang.Object): number;
							public getClassName(param0: java.lang.Object): string;
							public getContentDescription(param0: java.lang.Object): string;
							public getPackageName(param0: java.lang.Object): string;
							public getParent(param0: java.lang.Object): java.lang.Object;
							public getText(param0: java.lang.Object): string;
							public getWindowId(param0: java.lang.Object): number;
							public isCheckable(param0: java.lang.Object): boolean;
							public isChecked(param0: java.lang.Object): boolean;
							public isClickable(param0: java.lang.Object): boolean;
							public isEnabled(param0: java.lang.Object): boolean;
							public isFocusable(param0: java.lang.Object): boolean;
							public isFocused(param0: java.lang.Object): boolean;
							public isVisibleToUser(param0: java.lang.Object): boolean;
							public isAccessibilityFocused(param0: java.lang.Object): boolean;
							public isLongClickable(param0: java.lang.Object): boolean;
							public isPassword(param0: java.lang.Object): boolean;
							public isScrollable(param0: java.lang.Object): boolean;
							public isSelected(param0: java.lang.Object): boolean;
							public performAction(param0: java.lang.Object, param1: number): boolean;
							public performAction(param0: java.lang.Object, param1: number, param2: android.os.Bundle): boolean;
							public setMovementGranularities(param0: java.lang.Object, param1: number): void;
							public getMovementGranularities(param0: java.lang.Object): number;
							public setBoundsInParent(param0: java.lang.Object, param1: android.graphics.Rect): void;
							public setBoundsInScreen(param0: java.lang.Object, param1: android.graphics.Rect): void;
							public setCheckable(param0: java.lang.Object, param1: boolean): void;
							public setChecked(param0: java.lang.Object, param1: boolean): void;
							public setClassName(param0: java.lang.Object, param1: string): void;
							public setClickable(param0: java.lang.Object, param1: boolean): void;
							public setContentDescription(param0: java.lang.Object, param1: string): void;
							public setEnabled(param0: java.lang.Object, param1: boolean): void;
							public setFocusable(param0: java.lang.Object, param1: boolean): void;
							public setFocused(param0: java.lang.Object, param1: boolean): void;
							public setVisibleToUser(param0: java.lang.Object, param1: boolean): void;
							public setAccessibilityFocused(param0: java.lang.Object, param1: boolean): void;
							public setLongClickable(param0: java.lang.Object, param1: boolean): void;
							public setPackageName(param0: java.lang.Object, param1: string): void;
							public setParent(param0: java.lang.Object, param1: android.view.View): void;
							public setPassword(param0: java.lang.Object, param1: boolean): void;
							public setScrollable(param0: java.lang.Object, param1: boolean): void;
							public setSelected(param0: java.lang.Object, param1: boolean): void;
							public setSource(param0: java.lang.Object, param1: android.view.View): void;
							public setSource(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public findFocus(param0: java.lang.Object, param1: number): java.lang.Object;
							public focusSearch(param0: java.lang.Object, param1: number): java.lang.Object;
							public setText(param0: java.lang.Object, param1: string): void;
							public recycle(param0: java.lang.Object): void;
							public setParent(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public getViewIdResourceName(param0: java.lang.Object): string;
							public setViewIdResourceName(param0: java.lang.Object, param1: string): void;
							public getLiveRegion(param0: java.lang.Object): number;
							public setLiveRegion(param0: java.lang.Object, param1: number): void;
							public getCollectionInfo(param0: java.lang.Object): java.lang.Object;
							public setCollectionInfo(param0: java.lang.Object, param1: java.lang.Object): void;
							public getCollectionItemInfo(param0: java.lang.Object): java.lang.Object;
							public setCollectionItemInfo(param0: java.lang.Object, param1: java.lang.Object): void;
							public getRangeInfo(param0: java.lang.Object): java.lang.Object;
							public setRangeInfo(param0: java.lang.Object, param1: java.lang.Object): void;
							public getActionList(param0: java.lang.Object): java.util.List;
							public obtainCollectionInfo(param0: number, param1: number, param2: boolean, param3: number): java.lang.Object;
							public getCollectionInfoColumnCount(param0: java.lang.Object): number;
							public getCollectionInfoRowCount(param0: java.lang.Object): number;
							public isCollectionInfoHierarchical(param0: java.lang.Object): boolean;
							public obtainCollectionItemInfo(param0: number, param1: number, param2: number, param3: number, param4: boolean, param5: boolean): java.lang.Object;
							public getCollectionItemColumnIndex(param0: java.lang.Object): number;
							public getCollectionItemColumnSpan(param0: java.lang.Object): number;
							public getCollectionItemRowIndex(param0: java.lang.Object): number;
							public getCollectionItemRowSpan(param0: java.lang.Object): number;
							public isCollectionItemHeading(param0: java.lang.Object): boolean;
							public isCollectionItemSelected(param0: java.lang.Object): boolean;
							public getTraversalBefore(param0: java.lang.Object): java.lang.Object;
							public setTraversalBefore(param0: java.lang.Object, param1: android.view.View): void;
							public setTraversalBefore(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public getTraversalAfter(param0: java.lang.Object): java.lang.Object;
							public setTraversalAfter(param0: java.lang.Object, param1: android.view.View): void;
							public setTraversalAfter(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public setContentInvalid(param0: java.lang.Object, param1: boolean): void;
							public isContentInvalid(param0: java.lang.Object): boolean;
							public setError(param0: java.lang.Object, param1: string): void;
							public getError(param0: java.lang.Object): string;
							public setLabelFor(param0: java.lang.Object, param1: android.view.View): void;
							public setLabelFor(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public getLabelFor(param0: java.lang.Object): java.lang.Object;
							public setLabeledBy(param0: java.lang.Object, param1: android.view.View): void;
							public setLabeledBy(param0: java.lang.Object, param1: android.view.View, param2: number): void;
							public getLabeledBy(param0: java.lang.Object): java.lang.Object;
							public canOpenPopup(param0: java.lang.Object): boolean;
							public setCanOpenPopup(param0: java.lang.Object, param1: boolean): void;
							public findAccessibilityNodeInfosByViewId(param0: java.lang.Object, param1: string): java.util.List;
							public getExtras(param0: java.lang.Object): android.os.Bundle;
							public getInputType(param0: java.lang.Object): number;
							public setInputType(param0: java.lang.Object, param1: number): void;
							public setMaxTextLength(param0: java.lang.Object, param1: number): void;
							public getMaxTextLength(param0: java.lang.Object): number;
							public setTextSelection(param0: java.lang.Object, param1: number, param2: number): void;
							public getTextSelectionStart(param0: java.lang.Object): number;
							public getTextSelectionEnd(param0: java.lang.Object): number;
							public getWindow(param0: java.lang.Object): java.lang.Object;
							public isDismissable(param0: java.lang.Object): boolean;
							public setDismissable(param0: java.lang.Object, param1: boolean): void;
							public isEditable(param0: java.lang.Object): boolean;
							public setEditable(param0: java.lang.Object, param1: boolean): void;
							public isMultiLine(param0: java.lang.Object): boolean;
							public setMultiLine(param0: java.lang.Object, param1: boolean): void;
							public refresh(param0: java.lang.Object): boolean;
						}
						export class CollectionInfoCompat {
							public static obtain(param0: number, param1: number, param2: boolean, param3: number): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.CollectionInfoCompat;
							public getColumnCount(): number;
							public getRowCount(): number;
							public isHierarchical(): boolean;
							public static SELECTION_MODE_NONE: number;
							public static SELECTION_MODE_SINGLE: number;
							public static SELECTION_MODE_MULTIPLE: number;
						}
						export class CollectionItemInfoCompat {
							public static obtain(param0: number, param1: number, param2: number, param3: number, param4: boolean, param5: boolean): android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.CollectionItemInfoCompat;
							public getColumnIndex(): number;
							public getColumnSpan(): number;
							public getRowIndex(): number;
							public getRowSpan(): number;
							public isHeading(): boolean;
							public isSelected(): boolean;
						}
						export class RangeInfoCompat {
							public getCurrent(): number;
							public getMax(): number;
							public getMin(): number;
							public getType(): number;
							public static RANGE_TYPE_INT: number;
							public static RANGE_TYPE_FLOAT: number;
							public static RANGE_TYPE_PERCENT: number;
						}
					}
				}
			}
		}
	}
}
