/// <reference path="./_helpers.d.ts" />

declare module android {
	export module media {
		export class ToneGenerator {
			public constructor();
			public constructor(param0: number, param1: number);
			public startTone(param0: number): boolean;
			public startTone(param0: number, param1: number): boolean;
			public stopTone(): void;
			public release(): void;
			public getAudioSessionId(): number;
			public finalize(): void;
			public static MAX_VOLUME: number;
			public static MIN_VOLUME: number;
			public static TONE_CDMA_ABBR_ALERT: number;
			public static TONE_CDMA_ABBR_INTERCEPT: number;
			public static TONE_CDMA_ABBR_REORDER: number;
			public static TONE_CDMA_ALERT_AUTOREDIAL_LITE: number;
			public static TONE_CDMA_ALERT_CALL_GUARD: number;
			public static TONE_CDMA_ALERT_INCALL_LITE: number;
			public static TONE_CDMA_ALERT_NETWORK_LITE: number;
			public static TONE_CDMA_ANSWER: number;
			public static TONE_CDMA_CALLDROP_LITE: number;
			public static TONE_CDMA_CALL_SIGNAL_ISDN_INTERGROUP: number;
			public static TONE_CDMA_CALL_SIGNAL_ISDN_NORMAL: number;
			public static TONE_CDMA_CALL_SIGNAL_ISDN_PAT3: number;
			public static TONE_CDMA_CALL_SIGNAL_ISDN_PAT5: number;
			public static TONE_CDMA_CALL_SIGNAL_ISDN_PAT6: number;
			public static TONE_CDMA_CALL_SIGNAL_ISDN_PAT7: number;
			public static TONE_CDMA_CALL_SIGNAL_ISDN_PING_RING: number;
			public static TONE_CDMA_CALL_SIGNAL_ISDN_SP_PRI: number;
			public static TONE_CDMA_CONFIRM: number;
			public static TONE_CDMA_DIAL_TONE_LITE: number;
			public static TONE_CDMA_EMERGENCY_RINGBACK: number;
			public static TONE_CDMA_HIGH_L: number;
			public static TONE_CDMA_HIGH_PBX_L: number;
			public static TONE_CDMA_HIGH_PBX_SLS: number;
			public static TONE_CDMA_HIGH_PBX_SS: number;
			public static TONE_CDMA_HIGH_PBX_SSL: number;
			public static TONE_CDMA_HIGH_PBX_S_X4: number;
			public static TONE_CDMA_HIGH_SLS: number;
			public static TONE_CDMA_HIGH_SS: number;
			public static TONE_CDMA_HIGH_SSL: number;
			public static TONE_CDMA_HIGH_SS_2: number;
			public static TONE_CDMA_HIGH_S_X4: number;
			public static TONE_CDMA_INTERCEPT: number;
			public static TONE_CDMA_KEYPAD_VOLUME_KEY_LITE: number;
			public static TONE_CDMA_LOW_L: number;
			public static TONE_CDMA_LOW_PBX_L: number;
			public static TONE_CDMA_LOW_PBX_SLS: number;
			public static TONE_CDMA_LOW_PBX_SS: number;
			public static TONE_CDMA_LOW_PBX_SSL: number;
			public static TONE_CDMA_LOW_PBX_S_X4: number;
			public static TONE_CDMA_LOW_SLS: number;
			public static TONE_CDMA_LOW_SS: number;
			public static TONE_CDMA_LOW_SSL: number;
			public static TONE_CDMA_LOW_SS_2: number;
			public static TONE_CDMA_LOW_S_X4: number;
			public static TONE_CDMA_MED_L: number;
			public static TONE_CDMA_MED_PBX_L: number;
			public static TONE_CDMA_MED_PBX_SLS: number;
			public static TONE_CDMA_MED_PBX_SS: number;
			public static TONE_CDMA_MED_PBX_SSL: number;
			public static TONE_CDMA_MED_PBX_S_X4: number;
			public static TONE_CDMA_MED_SLS: number;
			public static TONE_CDMA_MED_SS: number;
			public static TONE_CDMA_MED_SSL: number;
			public static TONE_CDMA_MED_SS_2: number;
			public static TONE_CDMA_MED_S_X4: number;
			public static TONE_CDMA_NETWORK_BUSY: number;
			public static TONE_CDMA_NETWORK_BUSY_ONE_SHOT: number;
			public static TONE_CDMA_NETWORK_CALLWAITING: number;
			public static TONE_CDMA_NETWORK_USA_RINGBACK: number;
			public static TONE_CDMA_ONE_MIN_BEEP: number;
			public static TONE_CDMA_PIP: number;
			public static TONE_CDMA_PRESSHOLDKEY_LITE: number;
			public static TONE_CDMA_REORDER: number;
			public static TONE_CDMA_SIGNAL_OFF: number;
			public static TONE_CDMA_SOFT_ERROR_LITE: number;
			public static TONE_DTMF_0: number;
			public static TONE_DTMF_1: number;
			public static TONE_DTMF_2: number;
			public static TONE_DTMF_3: number;
			public static TONE_DTMF_4: number;
			public static TONE_DTMF_5: number;
			public static TONE_DTMF_6: number;
			public static TONE_DTMF_7: number;
			public static TONE_DTMF_8: number;
			public static TONE_DTMF_9: number;
			public static TONE_DTMF_A: number;
			public static TONE_DTMF_B: number;
			public static TONE_DTMF_C: number;
			public static TONE_DTMF_D: number;
			public static TONE_DTMF_P: number;
			public static TONE_DTMF_S: number;
			public static TONE_PROP_ACK: number;
			public static TONE_PROP_BEEP: number;
			public static TONE_PROP_BEEP2: number;
			public static TONE_PROP_NACK: number;
			public static TONE_PROP_PROMPT: number;
			public static TONE_SUP_BUSY: number;
			public static TONE_SUP_CALL_WAITING: number;
			public static TONE_SUP_CONFIRM: number;
			public static TONE_SUP_CONGESTION: number;
			public static TONE_SUP_CONGESTION_ABBREV: number;
			public static TONE_SUP_DIAL: number;
			public static TONE_SUP_ERROR: number;
			public static TONE_SUP_INTERCEPT: number;
			public static TONE_SUP_INTERCEPT_ABBREV: number;
			public static TONE_SUP_PIP: number;
			public static TONE_SUP_RADIO_ACK: number;
			public static TONE_SUP_RADIO_NOTAVAIL: number;
			public static TONE_SUP_RINGTONE: number;
		}
	}
}
