/// <reference path="./_helpers.d.ts" />
/// <reference path="./java.nio.Buffer.d.ts" />
/// <reference path="./java.nio.FloatBuffer.d.ts" />
/// <reference path="./java.nio.IntBuffer.d.ts" />

declare module android {
	export module opengl {
		export class GLES11 {
			public constructor();
			public static glBindBuffer(param0: number, param1: number): void;
			public static glBufferData(param0: number, param1: number, param2: java.nio.Buffer, param3: number): void;
			public static glBufferSubData(param0: number, param1: number, param2: number, param3: java.nio.Buffer): void;
			public static glClipPlanef(param0: number, param1: native.Array<number>, param2: number): void;
			public static glClipPlanef(param0: number, param1: java.nio.FloatBuffer): void;
			public static glClipPlanex(param0: number, param1: native.Array<number>, param2: number): void;
			public static glClipPlanex(param0: number, param1: java.nio.IntBuffer): void;
			public static glColor4ub(param0: number, param1: number, param2: number, param3: number): void;
			public static glColorPointer(param0: number, param1: number, param2: number, param3: java.nio.Buffer): void;
			public static glColorPointer(param0: number, param1: number, param2: number, param3: number): void;
			public static glDeleteBuffers(param0: number, param1: native.Array<number>, param2: number): void;
			public static glDeleteBuffers(param0: number, param1: java.nio.IntBuffer): void;
			public static glDrawElements(param0: number, param1: number, param2: number, param3: java.nio.Buffer): void;
			public static glDrawElements(param0: number, param1: number, param2: number, param3: number): void;
			public static glGenBuffers(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGenBuffers(param0: number, param1: java.nio.IntBuffer): void;
			public static glGetBooleanv(param0: number, param1: native.Array<boolean>, param2: number): void;
			public static glGetBooleanv(param0: number, param1: java.nio.IntBuffer): void;
			public static glGetBufferParameteriv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetBufferParameteriv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetClipPlanef(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGetClipPlanef(param0: number, param1: java.nio.FloatBuffer): void;
			public static glGetClipPlanex(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGetClipPlanex(param0: number, param1: java.nio.IntBuffer): void;
			public static glGetFixedv(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGetFixedv(param0: number, param1: java.nio.IntBuffer): void;
			public static glGetFloatv(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGetFloatv(param0: number, param1: java.nio.FloatBuffer): void;
			public static glGetLightfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetLightfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glGetLightxv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetLightxv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetMaterialfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetMaterialfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glGetMaterialxv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetMaterialxv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetTexEnvfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetTexEnvfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glGetTexEnviv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetTexEnviv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetTexEnvxv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetTexEnvxv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetTexParameterfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetTexParameterfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glGetTexParameteriv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetTexParameteriv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetTexParameterxv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetTexParameterxv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glIsBuffer(param0: number): boolean;
			public static glIsEnabled(param0: number): boolean;
			public static glIsTexture(param0: number): boolean;
			public static glNormalPointer(param0: number, param1: number, param2: java.nio.Buffer): void;
			public static glNormalPointer(param0: number, param1: number, param2: number): void;
			public static glPointParameterf(param0: number, param1: number): void;
			public static glPointParameterfv(param0: number, param1: native.Array<number>, param2: number): void;
			public static glPointParameterfv(param0: number, param1: java.nio.FloatBuffer): void;
			public static glPointParameterx(param0: number, param1: number): void;
			public static glPointParameterxv(param0: number, param1: native.Array<number>, param2: number): void;
			public static glPointParameterxv(param0: number, param1: java.nio.IntBuffer): void;
			public static glPointSizePointerOES(param0: number, param1: number, param2: java.nio.Buffer): void;
			public static glTexCoordPointer(param0: number, param1: number, param2: number, param3: java.nio.Buffer): void;
			public static glTexCoordPointer(param0: number, param1: number, param2: number, param3: number): void;
			public static glTexEnvi(param0: number, param1: number, param2: number): void;
			public static glTexEnviv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glTexEnviv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glTexParameterfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glTexParameterfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glTexParameteri(param0: number, param1: number, param2: number): void;
			public static glTexParameteriv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glTexParameteriv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glTexParameterxv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glTexParameterxv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glVertexPointer(param0: number, param1: number, param2: number, param3: java.nio.Buffer): void;
			public static glVertexPointer(param0: number, param1: number, param2: number, param3: number): void;
			public static GL_ACTIVE_TEXTURE: number;
			public static GL_ADD_SIGNED: number;
			public static GL_ALPHA_SCALE: number;
			public static GL_ALPHA_TEST_FUNC: number;
			public static GL_ALPHA_TEST_REF: number;
			public static GL_ARRAY_BUFFER: number;
			public static GL_ARRAY_BUFFER_BINDING: number;
			public static GL_BLEND_DST: number;
			public static GL_BLEND_SRC: number;
			public static GL_BUFFER_ACCESS: number;
			public static GL_BUFFER_SIZE: number;
			public static GL_BUFFER_USAGE: number;
			public static GL_CLIENT_ACTIVE_TEXTURE: number;
			public static GL_CLIP_PLANE0: number;
			public static GL_CLIP_PLANE1: number;
			public static GL_CLIP_PLANE2: number;
			public static GL_CLIP_PLANE3: number;
			public static GL_CLIP_PLANE4: number;
			public static GL_CLIP_PLANE5: number;
			public static GL_COLOR_ARRAY_BUFFER_BINDING: number;
			public static GL_COLOR_ARRAY_POINTER: number;
			public static GL_COLOR_ARRAY_SIZE: number;
			public static GL_COLOR_ARRAY_STRIDE: number;
			public static GL_COLOR_ARRAY_TYPE: number;
			public static GL_COLOR_CLEAR_VALUE: number;
			public static GL_COLOR_WRITEMASK: number;
			public static GL_COMBINE: number;
			public static GL_COMBINE_ALPHA: number;
			public static GL_COMBINE_RGB: number;
			public static GL_CONSTANT: number;
			public static GL_COORD_REPLACE_OES: number;
			public static GL_CULL_FACE_MODE: number;
			public static GL_CURRENT_COLOR: number;
			public static GL_CURRENT_NORMAL: number;
			public static GL_CURRENT_TEXTURE_COORDS: number;
			public static GL_DEPTH_CLEAR_VALUE: number;
			public static GL_DEPTH_FUNC: number;
			public static GL_DEPTH_RANGE: number;
			public static GL_DEPTH_WRITEMASK: number;
			public static GL_DOT3_RGB: number;
			public static GL_DOT3_RGBA: number;
			public static GL_DYNAMIC_DRAW: number;
			public static GL_ELEMENT_ARRAY_BUFFER: number;
			public static GL_ELEMENT_ARRAY_BUFFER_BINDING: number;
			public static GL_FRONT_FACE: number;
			public static GL_GENERATE_MIPMAP: number;
			public static GL_GENERATE_MIPMAP_HINT: number;
			public static GL_INTERPOLATE: number;
			public static GL_LINE_WIDTH: number;
			public static GL_LOGIC_OP_MODE: number;
			public static GL_MATRIX_MODE: number;
			public static GL_MAX_CLIP_PLANES: number;
			public static GL_MODELVIEW_MATRIX: number;
			public static GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES: number;
			public static GL_MODELVIEW_STACK_DEPTH: number;
			public static GL_NORMAL_ARRAY_BUFFER_BINDING: number;
			public static GL_NORMAL_ARRAY_POINTER: number;
			public static GL_NORMAL_ARRAY_STRIDE: number;
			public static GL_NORMAL_ARRAY_TYPE: number;
			public static GL_OPERAND0_ALPHA: number;
			public static GL_OPERAND0_RGB: number;
			public static GL_OPERAND1_ALPHA: number;
			public static GL_OPERAND1_RGB: number;
			public static GL_OPERAND2_ALPHA: number;
			public static GL_OPERAND2_RGB: number;
			public static GL_POINT_DISTANCE_ATTENUATION: number;
			public static GL_POINT_FADE_THRESHOLD_SIZE: number;
			public static GL_POINT_SIZE: number;
			public static GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES: number;
			public static GL_POINT_SIZE_ARRAY_OES: number;
			public static GL_POINT_SIZE_ARRAY_POINTER_OES: number;
			public static GL_POINT_SIZE_ARRAY_STRIDE_OES: number;
			public static GL_POINT_SIZE_ARRAY_TYPE_OES: number;
			public static GL_POINT_SIZE_MAX: number;
			public static GL_POINT_SIZE_MIN: number;
			public static GL_POINT_SPRITE_OES: number;
			public static GL_POLYGON_OFFSET_FACTOR: number;
			public static GL_POLYGON_OFFSET_UNITS: number;
			public static GL_PREVIOUS: number;
			public static GL_PRIMARY_COLOR: number;
			public static GL_PROJECTION_MATRIX: number;
			public static GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES: number;
			public static GL_PROJECTION_STACK_DEPTH: number;
			public static GL_RGB_SCALE: number;
			public static GL_SAMPLES: number;
			public static GL_SAMPLE_BUFFERS: number;
			public static GL_SAMPLE_COVERAGE_INVERT: number;
			public static GL_SAMPLE_COVERAGE_VALUE: number;
			public static GL_SCISSOR_BOX: number;
			public static GL_SHADE_MODEL: number;
			public static GL_SRC0_ALPHA: number;
			public static GL_SRC0_RGB: number;
			public static GL_SRC1_ALPHA: number;
			public static GL_SRC1_RGB: number;
			public static GL_SRC2_ALPHA: number;
			public static GL_SRC2_RGB: number;
			public static GL_STATIC_DRAW: number;
			public static GL_STENCIL_CLEAR_VALUE: number;
			public static GL_STENCIL_FAIL: number;
			public static GL_STENCIL_FUNC: number;
			public static GL_STENCIL_PASS_DEPTH_FAIL: number;
			public static GL_STENCIL_PASS_DEPTH_PASS: number;
			public static GL_STENCIL_REF: number;
			public static GL_STENCIL_VALUE_MASK: number;
			public static GL_STENCIL_WRITEMASK: number;
			public static GL_SUBTRACT: number;
			public static GL_TEXTURE_BINDING_2D: number;
			public static GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING: number;
			public static GL_TEXTURE_COORD_ARRAY_POINTER: number;
			public static GL_TEXTURE_COORD_ARRAY_SIZE: number;
			public static GL_TEXTURE_COORD_ARRAY_STRIDE: number;
			public static GL_TEXTURE_COORD_ARRAY_TYPE: number;
			public static GL_TEXTURE_MATRIX: number;
			public static GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES: number;
			public static GL_TEXTURE_STACK_DEPTH: number;
			public static GL_VERTEX_ARRAY_BUFFER_BINDING: number;
			public static GL_VERTEX_ARRAY_POINTER: number;
			public static GL_VERTEX_ARRAY_SIZE: number;
			public static GL_VERTEX_ARRAY_STRIDE: number;
			public static GL_VERTEX_ARRAY_TYPE: number;
			public static GL_VIEWPORT: number;
			public static GL_WRITE_ONLY: number;
		}
	}
}
