/// <reference path="./_helpers.d.ts" />
/// <reference path="./android.opengl.EGLConfig.d.ts" />
/// <reference path="./android.opengl.EGLContext.d.ts" />
/// <reference path="./android.opengl.EGLDisplay.d.ts" />
/// <reference path="./android.opengl.EGLSurface.d.ts" />
/// <reference path="./java.lang.Object.d.ts" />

declare module android {
	export module opengl {
		export class EGL14 {
			public constructor();
			public static eglGetError(): number;
			public static eglGetDisplay(param0: number): android.opengl.EGLDisplay;
			public static eglInitialize(param0: android.opengl.EGLDisplay, param1: native.Array<number>, param2: number, param3: native.Array<number>, param4: number): boolean;
			public static eglTerminate(param0: android.opengl.EGLDisplay): boolean;
			public static eglQueryString(param0: android.opengl.EGLDisplay, param1: number): string;
			public static eglGetConfigs(param0: android.opengl.EGLDisplay, param1: native.Array<android.opengl.EGLConfig>, param2: number, param3: number, param4: native.Array<number>, param5: number): boolean;
			public static eglChooseConfig(param0: android.opengl.EGLDisplay, param1: native.Array<number>, param2: number, param3: native.Array<android.opengl.EGLConfig>, param4: number, param5: number, param6: native.Array<number>, param7: number): boolean;
			public static eglGetConfigAttrib(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLConfig, param2: number, param3: native.Array<number>, param4: number): boolean;
			public static eglCreateWindowSurface(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLConfig, param2: java.lang.Object, param3: native.Array<number>, param4: number): android.opengl.EGLSurface;
			public static eglCreatePbufferSurface(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLConfig, param2: native.Array<number>, param3: number): android.opengl.EGLSurface;
			public static eglCreatePixmapSurface(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLConfig, param2: number, param3: native.Array<number>, param4: number): android.opengl.EGLSurface;
			public static eglDestroySurface(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLSurface): boolean;
			public static eglQuerySurface(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLSurface, param2: number, param3: native.Array<number>, param4: number): boolean;
			public static eglBindAPI(param0: number): boolean;
			public static eglQueryAPI(): number;
			public static eglWaitClient(): boolean;
			public static eglReleaseThread(): boolean;
			public static eglCreatePbufferFromClientBuffer(param0: android.opengl.EGLDisplay, param1: number, param2: number, param3: android.opengl.EGLConfig, param4: native.Array<number>, param5: number): android.opengl.EGLSurface;
			public static eglSurfaceAttrib(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLSurface, param2: number, param3: number): boolean;
			public static eglBindTexImage(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLSurface, param2: number): boolean;
			public static eglReleaseTexImage(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLSurface, param2: number): boolean;
			public static eglSwapInterval(param0: android.opengl.EGLDisplay, param1: number): boolean;
			public static eglCreateContext(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLConfig, param2: android.opengl.EGLContext, param3: native.Array<number>, param4: number): android.opengl.EGLContext;
			public static eglDestroyContext(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLContext): boolean;
			public static eglMakeCurrent(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLSurface, param2: android.opengl.EGLSurface, param3: android.opengl.EGLContext): boolean;
			public static eglGetCurrentContext(): android.opengl.EGLContext;
			public static eglGetCurrentSurface(param0: number): android.opengl.EGLSurface;
			public static eglGetCurrentDisplay(): android.opengl.EGLDisplay;
			public static eglQueryContext(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLContext, param2: number, param3: native.Array<number>, param4: number): boolean;
			public static eglWaitGL(): boolean;
			public static eglWaitNative(param0: number): boolean;
			public static eglSwapBuffers(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLSurface): boolean;
			public static eglCopyBuffers(param0: android.opengl.EGLDisplay, param1: android.opengl.EGLSurface, param2: number): boolean;
			public static EGL_ALPHA_MASK_SIZE: number;
			public static EGL_ALPHA_SIZE: number;
			public static EGL_BACK_BUFFER: number;
			public static EGL_BAD_ACCESS: number;
			public static EGL_BAD_ALLOC: number;
			public static EGL_BAD_ATTRIBUTE: number;
			public static EGL_BAD_CONFIG: number;
			public static EGL_BAD_CONTEXT: number;
			public static EGL_BAD_CURRENT_SURFACE: number;
			public static EGL_BAD_DISPLAY: number;
			public static EGL_BAD_MATCH: number;
			public static EGL_BAD_NATIVE_PIXMAP: number;
			public static EGL_BAD_NATIVE_WINDOW: number;
			public static EGL_BAD_PARAMETER: number;
			public static EGL_BAD_SURFACE: number;
			public static EGL_BIND_TO_TEXTURE_RGB: number;
			public static EGL_BIND_TO_TEXTURE_RGBA: number;
			public static EGL_BLUE_SIZE: number;
			public static EGL_BUFFER_DESTROYED: number;
			public static EGL_BUFFER_PRESERVED: number;
			public static EGL_BUFFER_SIZE: number;
			public static EGL_CLIENT_APIS: number;
			public static EGL_COLOR_BUFFER_TYPE: number;
			public static EGL_CONFIG_CAVEAT: number;
			public static EGL_CONFIG_ID: number;
			public static EGL_CONFORMANT: number;
			public static EGL_CONTEXT_CLIENT_TYPE: number;
			public static EGL_CONTEXT_CLIENT_VERSION: number;
			public static EGL_CONTEXT_LOST: number;
			public static EGL_CORE_NATIVE_ENGINE: number;
			public static EGL_DEFAULT_DISPLAY: number;
			public static EGL_DEPTH_SIZE: number;
			public static EGL_DISPLAY_SCALING: number;
			public static EGL_DRAW: number;
			public static EGL_EXTENSIONS: number;
			public static EGL_FALSE: number;
			public static EGL_GREEN_SIZE: number;
			public static EGL_HEIGHT: number;
			public static EGL_HORIZONTAL_RESOLUTION: number;
			public static EGL_LARGEST_PBUFFER: number;
			public static EGL_LEVEL: number;
			public static EGL_LUMINANCE_BUFFER: number;
			public static EGL_LUMINANCE_SIZE: number;
			public static EGL_MATCH_NATIVE_PIXMAP: number;
			public static EGL_MAX_PBUFFER_HEIGHT: number;
			public static EGL_MAX_PBUFFER_PIXELS: number;
			public static EGL_MAX_PBUFFER_WIDTH: number;
			public static EGL_MAX_SWAP_INTERVAL: number;
			public static EGL_MIN_SWAP_INTERVAL: number;
			public static EGL_MIPMAP_LEVEL: number;
			public static EGL_MIPMAP_TEXTURE: number;
			public static EGL_MULTISAMPLE_RESOLVE: number;
			public static EGL_MULTISAMPLE_RESOLVE_BOX: number;
			public static EGL_MULTISAMPLE_RESOLVE_BOX_BIT: number;
			public static EGL_MULTISAMPLE_RESOLVE_DEFAULT: number;
			public static EGL_NATIVE_RENDERABLE: number;
			public static EGL_NATIVE_VISUAL_ID: number;
			public static EGL_NATIVE_VISUAL_TYPE: number;
			public static EGL_NONE: number;
			public static EGL_NON_CONFORMANT_CONFIG: number;
			public static EGL_NOT_INITIALIZED: number;
			public static EGL_NO_CONTEXT: android.opengl.EGLContext;
			public static EGL_NO_DISPLAY: android.opengl.EGLDisplay;
			public static EGL_NO_SURFACE: android.opengl.EGLSurface;
			public static EGL_NO_TEXTURE: number;
			public static EGL_OPENGL_API: number;
			public static EGL_OPENGL_BIT: number;
			public static EGL_OPENGL_ES2_BIT: number;
			public static EGL_OPENGL_ES_API: number;
			public static EGL_OPENGL_ES_BIT: number;
			public static EGL_OPENVG_API: number;
			public static EGL_OPENVG_BIT: number;
			public static EGL_OPENVG_IMAGE: number;
			public static EGL_PBUFFER_BIT: number;
			public static EGL_PIXEL_ASPECT_RATIO: number;
			public static EGL_PIXMAP_BIT: number;
			public static EGL_READ: number;
			public static EGL_RED_SIZE: number;
			public static EGL_RENDERABLE_TYPE: number;
			public static EGL_RENDER_BUFFER: number;
			public static EGL_RGB_BUFFER: number;
			public static EGL_SAMPLES: number;
			public static EGL_SAMPLE_BUFFERS: number;
			public static EGL_SINGLE_BUFFER: number;
			public static EGL_SLOW_CONFIG: number;
			public static EGL_STENCIL_SIZE: number;
			public static EGL_SUCCESS: number;
			public static EGL_SURFACE_TYPE: number;
			public static EGL_SWAP_BEHAVIOR: number;
			public static EGL_SWAP_BEHAVIOR_PRESERVED_BIT: number;
			public static EGL_TEXTURE_2D: number;
			public static EGL_TEXTURE_FORMAT: number;
			public static EGL_TEXTURE_RGB: number;
			public static EGL_TEXTURE_RGBA: number;
			public static EGL_TEXTURE_TARGET: number;
			public static EGL_TRANSPARENT_BLUE_VALUE: number;
			public static EGL_TRANSPARENT_GREEN_VALUE: number;
			public static EGL_TRANSPARENT_RED_VALUE: number;
			public static EGL_TRANSPARENT_RGB: number;
			public static EGL_TRANSPARENT_TYPE: number;
			public static EGL_TRUE: number;
			public static EGL_VENDOR: number;
			public static EGL_VERSION: number;
			public static EGL_VERTICAL_RESOLUTION: number;
			public static EGL_VG_ALPHA_FORMAT: number;
			public static EGL_VG_ALPHA_FORMAT_NONPRE: number;
			public static EGL_VG_ALPHA_FORMAT_PRE: number;
			public static EGL_VG_ALPHA_FORMAT_PRE_BIT: number;
			public static EGL_VG_COLORSPACE: number;
			public static EGL_VG_COLORSPACE_LINEAR: number;
			public static EGL_VG_COLORSPACE_LINEAR_BIT: number;
			public static EGL_VG_COLORSPACE_sRGB: number;
			public static EGL_WIDTH: number;
			public static EGL_WINDOW_BIT: number;
		}
	}
}
