/// <reference path="./_helpers.d.ts" />
/// <reference path="./java.lang.String.d.ts" />
/// <reference path="./java.nio.FloatBuffer.d.ts" />
/// <reference path="./java.nio.IntBuffer.d.ts" />

declare module android {
	export module opengl {
		export class GLES31 {
			public static glDispatchCompute(param0: number, param1: number, param2: number): void;
			public static glDispatchComputeIndirect(param0: number): void;
			public static glDrawArraysIndirect(param0: number, param1: number): void;
			public static glDrawElementsIndirect(param0: number, param1: number, param2: number): void;
			public static glFramebufferParameteri(param0: number, param1: number, param2: number): void;
			public static glGetFramebufferParameteriv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetFramebufferParameteriv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetProgramInterfaceiv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glGetProgramInterfaceiv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer): void;
			public static glGetProgramResourceIndex(param0: number, param1: number, param2: string): number;
			public static glGetProgramResourceName(param0: number, param1: number, param2: number): string;
			public static glGetProgramResourceiv(param0: number, param1: number, param2: number, param3: number, param4: native.Array<number>, param5: number, param6: number, param7: native.Array<number>, param8: number, param9: native.Array<number>, param10: number): void;
			public static glGetProgramResourceiv(param0: number, param1: number, param2: number, param3: number, param4: java.nio.IntBuffer, param5: number, param6: java.nio.IntBuffer, param7: java.nio.IntBuffer): void;
			public static glGetProgramResourceLocation(param0: number, param1: number, param2: string): number;
			public static glUseProgramStages(param0: number, param1: number, param2: number): void;
			public static glActiveShaderProgram(param0: number, param1: number): void;
			public static glCreateShaderProgramv(param0: number, param1: native.Array<string>): number;
			public static glBindProgramPipeline(param0: number): void;
			public static glDeleteProgramPipelines(param0: number, param1: native.Array<number>, param2: number): void;
			public static glDeleteProgramPipelines(param0: number, param1: java.nio.IntBuffer): void;
			public static glGenProgramPipelines(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGenProgramPipelines(param0: number, param1: java.nio.IntBuffer): void;
			public static glIsProgramPipeline(param0: number): boolean;
			public static glGetProgramPipelineiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetProgramPipelineiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glProgramUniform1i(param0: number, param1: number, param2: number): void;
			public static glProgramUniform2i(param0: number, param1: number, param2: number, param3: number): void;
			public static glProgramUniform3i(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glProgramUniform4i(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number): void;
			public static glProgramUniform1ui(param0: number, param1: number, param2: number): void;
			public static glProgramUniform2ui(param0: number, param1: number, param2: number, param3: number): void;
			public static glProgramUniform3ui(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glProgramUniform4ui(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number): void;
			public static glProgramUniform1f(param0: number, param1: number, param2: number): void;
			public static glProgramUniform2f(param0: number, param1: number, param2: number, param3: number): void;
			public static glProgramUniform3f(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glProgramUniform4f(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number): void;
			public static glProgramUniform1iv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glProgramUniform1iv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer): void;
			public static glProgramUniform2iv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glProgramUniform2iv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer): void;
			public static glProgramUniform3iv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glProgramUniform3iv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer): void;
			public static glProgramUniform4iv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glProgramUniform4iv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer): void;
			public static glProgramUniform1uiv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glProgramUniform1uiv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer): void;
			public static glProgramUniform2uiv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glProgramUniform2uiv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer): void;
			public static glProgramUniform3uiv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glProgramUniform3uiv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer): void;
			public static glProgramUniform4uiv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glProgramUniform4uiv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer): void;
			public static glProgramUniform1fv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glProgramUniform1fv(param0: number, param1: number, param2: number, param3: java.nio.FloatBuffer): void;
			public static glProgramUniform2fv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glProgramUniform2fv(param0: number, param1: number, param2: number, param3: java.nio.FloatBuffer): void;
			public static glProgramUniform3fv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glProgramUniform3fv(param0: number, param1: number, param2: number, param3: java.nio.FloatBuffer): void;
			public static glProgramUniform4fv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glProgramUniform4fv(param0: number, param1: number, param2: number, param3: java.nio.FloatBuffer): void;
			public static glProgramUniformMatrix2fv(param0: number, param1: number, param2: number, param3: boolean, param4: native.Array<number>, param5: number): void;
			public static glProgramUniformMatrix2fv(param0: number, param1: number, param2: number, param3: boolean, param4: java.nio.FloatBuffer): void;
			public static glProgramUniformMatrix3fv(param0: number, param1: number, param2: number, param3: boolean, param4: native.Array<number>, param5: number): void;
			public static glProgramUniformMatrix3fv(param0: number, param1: number, param2: number, param3: boolean, param4: java.nio.FloatBuffer): void;
			public static glProgramUniformMatrix4fv(param0: number, param1: number, param2: number, param3: boolean, param4: native.Array<number>, param5: number): void;
			public static glProgramUniformMatrix4fv(param0: number, param1: number, param2: number, param3: boolean, param4: java.nio.FloatBuffer): void;
			public static glProgramUniformMatrix2x3fv(param0: number, param1: number, param2: number, param3: boolean, param4: native.Array<number>, param5: number): void;
			public static glProgramUniformMatrix2x3fv(param0: number, param1: number, param2: number, param3: boolean, param4: java.nio.FloatBuffer): void;
			public static glProgramUniformMatrix3x2fv(param0: number, param1: number, param2: number, param3: boolean, param4: native.Array<number>, param5: number): void;
			public static glProgramUniformMatrix3x2fv(param0: number, param1: number, param2: number, param3: boolean, param4: java.nio.FloatBuffer): void;
			public static glProgramUniformMatrix2x4fv(param0: number, param1: number, param2: number, param3: boolean, param4: native.Array<number>, param5: number): void;
			public static glProgramUniformMatrix2x4fv(param0: number, param1: number, param2: number, param3: boolean, param4: java.nio.FloatBuffer): void;
			public static glProgramUniformMatrix4x2fv(param0: number, param1: number, param2: number, param3: boolean, param4: native.Array<number>, param5: number): void;
			public static glProgramUniformMatrix4x2fv(param0: number, param1: number, param2: number, param3: boolean, param4: java.nio.FloatBuffer): void;
			public static glProgramUniformMatrix3x4fv(param0: number, param1: number, param2: number, param3: boolean, param4: native.Array<number>, param5: number): void;
			public static glProgramUniformMatrix3x4fv(param0: number, param1: number, param2: number, param3: boolean, param4: java.nio.FloatBuffer): void;
			public static glProgramUniformMatrix4x3fv(param0: number, param1: number, param2: number, param3: boolean, param4: native.Array<number>, param5: number): void;
			public static glProgramUniformMatrix4x3fv(param0: number, param1: number, param2: number, param3: boolean, param4: java.nio.FloatBuffer): void;
			public static glValidateProgramPipeline(param0: number): void;
			public static glGetProgramPipelineInfoLog(param0: number): string;
			public static glBindImageTexture(param0: number, param1: number, param2: number, param3: boolean, param4: number, param5: number, param6: number): void;
			public static glGetBooleani_v(param0: number, param1: number, param2: native.Array<boolean>, param3: number): void;
			public static glGetBooleani_v(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glMemoryBarrier(param0: number): void;
			public static glMemoryBarrierByRegion(param0: number): void;
			public static glTexStorage2DMultisample(param0: number, param1: number, param2: number, param3: number, param4: number, param5: boolean): void;
			public static glGetMultisamplefv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetMultisamplefv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glSampleMaski(param0: number, param1: number): void;
			public static glGetTexLevelParameteriv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glGetTexLevelParameteriv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer): void;
			public static glGetTexLevelParameterfv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glGetTexLevelParameterfv(param0: number, param1: number, param2: number, param3: java.nio.FloatBuffer): void;
			public static glBindVertexBuffer(param0: number, param1: number, param2: number, param3: number): void;
			public static glVertexAttribFormat(param0: number, param1: number, param2: number, param3: boolean, param4: number): void;
			public static glVertexAttribIFormat(param0: number, param1: number, param2: number, param3: number): void;
			public static glVertexAttribBinding(param0: number, param1: number): void;
			public static glVertexBindingDivisor(param0: number, param1: number): void;
			public static GL_ACTIVE_ATOMIC_COUNTER_BUFFERS: number;
			public static GL_ACTIVE_PROGRAM: number;
			public static GL_ACTIVE_RESOURCES: number;
			public static GL_ACTIVE_VARIABLES: number;
			public static GL_ALL_SHADER_BITS: number;
			public static GL_ARRAY_SIZE: number;
			public static GL_ARRAY_STRIDE: number;
			public static GL_ATOMIC_COUNTER_BARRIER_BIT: number;
			public static GL_ATOMIC_COUNTER_BUFFER: number;
			public static GL_ATOMIC_COUNTER_BUFFER_BINDING: number;
			public static GL_ATOMIC_COUNTER_BUFFER_INDEX: number;
			public static GL_ATOMIC_COUNTER_BUFFER_SIZE: number;
			public static GL_ATOMIC_COUNTER_BUFFER_START: number;
			public static GL_BLOCK_INDEX: number;
			public static GL_BUFFER_BINDING: number;
			public static GL_BUFFER_DATA_SIZE: number;
			public static GL_BUFFER_UPDATE_BARRIER_BIT: number;
			public static GL_BUFFER_VARIABLE: number;
			public static GL_COMMAND_BARRIER_BIT: number;
			public static GL_COMPUTE_SHADER: number;
			public static GL_COMPUTE_SHADER_BIT: number;
			public static GL_COMPUTE_WORK_GROUP_SIZE: number;
			public static GL_DEPTH_STENCIL_TEXTURE_MODE: number;
			public static GL_DISPATCH_INDIRECT_BUFFER: number;
			public static GL_DISPATCH_INDIRECT_BUFFER_BINDING: number;
			public static GL_DRAW_INDIRECT_BUFFER: number;
			public static GL_DRAW_INDIRECT_BUFFER_BINDING: number;
			public static GL_FRAGMENT_SHADER_BIT: number;
			public static GL_FRAMEBUFFER_BARRIER_BIT: number;
			public static GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS: number;
			public static GL_FRAMEBUFFER_DEFAULT_HEIGHT: number;
			public static GL_FRAMEBUFFER_DEFAULT_SAMPLES: number;
			public static GL_FRAMEBUFFER_DEFAULT_WIDTH: number;
			public static GL_IMAGE_2D: number;
			public static GL_IMAGE_2D_ARRAY: number;
			public static GL_IMAGE_3D: number;
			public static GL_IMAGE_BINDING_ACCESS: number;
			public static GL_IMAGE_BINDING_FORMAT: number;
			public static GL_IMAGE_BINDING_LAYER: number;
			public static GL_IMAGE_BINDING_LAYERED: number;
			public static GL_IMAGE_BINDING_LEVEL: number;
			public static GL_IMAGE_BINDING_NAME: number;
			public static GL_IMAGE_CUBE: number;
			public static GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS: number;
			public static GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE: number;
			public static GL_IMAGE_FORMAT_COMPATIBILITY_TYPE: number;
			public static GL_INT_IMAGE_2D: number;
			public static GL_INT_IMAGE_2D_ARRAY: number;
			public static GL_INT_IMAGE_3D: number;
			public static GL_INT_IMAGE_CUBE: number;
			public static GL_INT_SAMPLER_2D_MULTISAMPLE: number;
			public static GL_IS_ROW_MAJOR: number;
			public static GL_LOCATION: number;
			public static GL_MATRIX_STRIDE: number;
			public static GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS: number;
			public static GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE: number;
			public static GL_MAX_COLOR_TEXTURE_SAMPLES: number;
			public static GL_MAX_COMBINED_ATOMIC_COUNTERS: number;
			public static GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS: number;
			public static GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS: number;
			public static GL_MAX_COMBINED_IMAGE_UNIFORMS: number;
			public static GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES: number;
			public static GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS: number;
			public static GL_MAX_COMPUTE_ATOMIC_COUNTERS: number;
			public static GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS: number;
			public static GL_MAX_COMPUTE_IMAGE_UNIFORMS: number;
			public static GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS: number;
			public static GL_MAX_COMPUTE_SHARED_MEMORY_SIZE: number;
			public static GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS: number;
			public static GL_MAX_COMPUTE_UNIFORM_BLOCKS: number;
			public static GL_MAX_COMPUTE_UNIFORM_COMPONENTS: number;
			public static GL_MAX_COMPUTE_WORK_GROUP_COUNT: number;
			public static GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS: number;
			public static GL_MAX_COMPUTE_WORK_GROUP_SIZE: number;
			public static GL_MAX_DEPTH_TEXTURE_SAMPLES: number;
			public static GL_MAX_FRAGMENT_ATOMIC_COUNTERS: number;
			public static GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS: number;
			public static GL_MAX_FRAGMENT_IMAGE_UNIFORMS: number;
			public static GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS: number;
			public static GL_MAX_FRAMEBUFFER_HEIGHT: number;
			public static GL_MAX_FRAMEBUFFER_SAMPLES: number;
			public static GL_MAX_FRAMEBUFFER_WIDTH: number;
			public static GL_MAX_IMAGE_UNITS: number;
			public static GL_MAX_INTEGER_SAMPLES: number;
			public static GL_MAX_NAME_LENGTH: number;
			public static GL_MAX_NUM_ACTIVE_VARIABLES: number;
			public static GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET: number;
			public static GL_MAX_SAMPLE_MASK_WORDS: number;
			public static GL_MAX_SHADER_STORAGE_BLOCK_SIZE: number;
			public static GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS: number;
			public static GL_MAX_UNIFORM_LOCATIONS: number;
			public static GL_MAX_VERTEX_ATOMIC_COUNTERS: number;
			public static GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS: number;
			public static GL_MAX_VERTEX_ATTRIB_BINDINGS: number;
			public static GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET: number;
			public static GL_MAX_VERTEX_ATTRIB_STRIDE: number;
			public static GL_MAX_VERTEX_IMAGE_UNIFORMS: number;
			public static GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS: number;
			public static GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET: number;
			public static GL_NAME_LENGTH: number;
			public static GL_NUM_ACTIVE_VARIABLES: number;
			public static GL_OFFSET: number;
			public static GL_PIXEL_BUFFER_BARRIER_BIT: number;
			public static GL_PROGRAM_INPUT: number;
			public static GL_PROGRAM_OUTPUT: number;
			public static GL_PROGRAM_PIPELINE_BINDING: number;
			public static GL_PROGRAM_SEPARABLE: number;
			public static GL_READ_ONLY: number;
			public static GL_READ_WRITE: number;
			public static GL_REFERENCED_BY_COMPUTE_SHADER: number;
			public static GL_REFERENCED_BY_FRAGMENT_SHADER: number;
			public static GL_REFERENCED_BY_VERTEX_SHADER: number;
			public static GL_SAMPLER_2D_MULTISAMPLE: number;
			public static GL_SAMPLE_MASK: number;
			public static GL_SAMPLE_MASK_VALUE: number;
			public static GL_SAMPLE_POSITION: number;
			public static GL_SHADER_STORAGE_BARRIER_BIT: number;
			public static GL_SHADER_STORAGE_BLOCK: number;
			public static GL_SHADER_STORAGE_BUFFER: number;
			public static GL_SHADER_STORAGE_BUFFER_BINDING: number;
			public static GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT: number;
			public static GL_SHADER_STORAGE_BUFFER_SIZE: number;
			public static GL_SHADER_STORAGE_BUFFER_START: number;
			public static GL_STENCIL_INDEX: number;
			public static GL_TEXTURE_2D_MULTISAMPLE: number;
			public static GL_TEXTURE_ALPHA_SIZE: number;
			public static GL_TEXTURE_ALPHA_TYPE: number;
			public static GL_TEXTURE_BINDING_2D_MULTISAMPLE: number;
			public static GL_TEXTURE_BLUE_SIZE: number;
			public static GL_TEXTURE_BLUE_TYPE: number;
			public static GL_TEXTURE_COMPRESSED: number;
			public static GL_TEXTURE_DEPTH: number;
			public static GL_TEXTURE_DEPTH_SIZE: number;
			public static GL_TEXTURE_DEPTH_TYPE: number;
			public static GL_TEXTURE_FETCH_BARRIER_BIT: number;
			public static GL_TEXTURE_FIXED_SAMPLE_LOCATIONS: number;
			public static GL_TEXTURE_GREEN_SIZE: number;
			public static GL_TEXTURE_GREEN_TYPE: number;
			public static GL_TEXTURE_HEIGHT: number;
			public static GL_TEXTURE_INTERNAL_FORMAT: number;
			public static GL_TEXTURE_RED_SIZE: number;
			public static GL_TEXTURE_RED_TYPE: number;
			public static GL_TEXTURE_SAMPLES: number;
			public static GL_TEXTURE_SHARED_SIZE: number;
			public static GL_TEXTURE_STENCIL_SIZE: number;
			public static GL_TEXTURE_UPDATE_BARRIER_BIT: number;
			public static GL_TEXTURE_WIDTH: number;
			public static GL_TOP_LEVEL_ARRAY_SIZE: number;
			public static GL_TOP_LEVEL_ARRAY_STRIDE: number;
			public static GL_TRANSFORM_FEEDBACK_BARRIER_BIT: number;
			public static GL_TRANSFORM_FEEDBACK_VARYING: number;
			public static GL_TYPE: number;
			public static GL_UNIFORM: number;
			public static GL_UNIFORM_BARRIER_BIT: number;
			public static GL_UNIFORM_BLOCK: number;
			public static GL_UNSIGNED_INT_ATOMIC_COUNTER: number;
			public static GL_UNSIGNED_INT_IMAGE_2D: number;
			public static GL_UNSIGNED_INT_IMAGE_2D_ARRAY: number;
			public static GL_UNSIGNED_INT_IMAGE_3D: number;
			public static GL_UNSIGNED_INT_IMAGE_CUBE: number;
			public static GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE: number;
			public static GL_VERTEX_ATTRIB_BINDING: number;
			public static GL_VERTEX_ATTRIB_RELATIVE_OFFSET: number;
			public static GL_VERTEX_BINDING_BUFFER: number;
			public static GL_VERTEX_BINDING_DIVISOR: number;
			public static GL_VERTEX_BINDING_OFFSET: number;
			public static GL_VERTEX_BINDING_STRIDE: number;
			public static GL_VERTEX_SHADER_BIT: number;
			public static GL_WRITE_ONLY: number;
		}
	}
}
