/// <reference path="./_helpers.d.ts" />

declare module android {
	export module mtp {
		export class MtpConstants {
			public constructor();
			public static isAbstractObject(param0: number): boolean;
			public static ASSOCIATION_TYPE_GENERIC_FOLDER: number;
			public static FORMAT_3GP_CONTAINER: number;
			public static FORMAT_AAC: number;
			public static FORMAT_ABSTRACT_AUDIO_ALBUM: number;
			public static FORMAT_ABSTRACT_AUDIO_PLAYLIST: number;
			public static FORMAT_ABSTRACT_AV_PLAYLIST: number;
			public static FORMAT_ABSTRACT_DOCUMENT: number;
			public static FORMAT_ABSTRACT_IMAGE_ALBUM: number;
			public static FORMAT_ABSTRACT_MEDIACAST: number;
			public static FORMAT_ABSTRACT_MULTIMEDIA_ALBUM: number;
			public static FORMAT_ABSTRACT_VIDEO_ALBUM: number;
			public static FORMAT_ABSTRACT_VIDEO_PLAYLIST: number;
			public static FORMAT_AIFF: number;
			public static FORMAT_ASF: number;
			public static FORMAT_ASSOCIATION: number;
			public static FORMAT_ASX_PLAYLIST: number;
			public static FORMAT_AUDIBLE: number;
			public static FORMAT_AVI: number;
			public static FORMAT_BMP: number;
			public static FORMAT_DPOF: number;
			public static FORMAT_EXECUTABLE: number;
			public static FORMAT_EXIF_JPEG: number;
			public static FORMAT_FLAC: number;
			public static FORMAT_GIF: number;
			public static FORMAT_HTML: number;
			public static FORMAT_JFIF: number;
			public static FORMAT_JP2: number;
			public static FORMAT_JPX: number;
			public static FORMAT_M3U_PLAYLIST: number;
			public static FORMAT_MP2: number;
			public static FORMAT_MP3: number;
			public static FORMAT_MP4_CONTAINER: number;
			public static FORMAT_MPEG: number;
			public static FORMAT_MPL_PLAYLIST: number;
			public static FORMAT_MS_EXCEL_SPREADSHEET: number;
			public static FORMAT_MS_POWERPOINT_PRESENTATION: number;
			public static FORMAT_MS_WORD_DOCUMENT: number;
			public static FORMAT_OGG: number;
			public static FORMAT_PICT: number;
			public static FORMAT_PLS_PLAYLIST: number;
			public static FORMAT_PNG: number;
			public static FORMAT_SCRIPT: number;
			public static FORMAT_TEXT: number;
			public static FORMAT_TIFF: number;
			public static FORMAT_TIFF_EP: number;
			public static FORMAT_UNDEFINED: number;
			public static FORMAT_UNDEFINED_AUDIO: number;
			public static FORMAT_UNDEFINED_COLLECTION: number;
			public static FORMAT_UNDEFINED_DOCUMENT: number;
			public static FORMAT_UNDEFINED_FIRMWARE: number;
			public static FORMAT_UNDEFINED_VIDEO: number;
			public static FORMAT_WAV: number;
			public static FORMAT_WINDOWS_IMAGE_FORMAT: number;
			public static FORMAT_WMA: number;
			public static FORMAT_WMV: number;
			public static FORMAT_WPL_PLAYLIST: number;
			public static FORMAT_XML_DOCUMENT: number;
			public static PROTECTION_STATUS_NONE: number;
			public static PROTECTION_STATUS_NON_TRANSFERABLE_DATA: number;
			public static PROTECTION_STATUS_READ_ONLY: number;
			public static PROTECTION_STATUS_READ_ONLY_DATA: number;
		}
	}
}
