/// <reference path="./_helpers.d.ts" />
/// <reference path="./java.lang.String.d.ts" />
/// <reference path="./java.nio.Buffer.d.ts" />
/// <reference path="./java.nio.FloatBuffer.d.ts" />
/// <reference path="./java.nio.IntBuffer.d.ts" />

declare module android {
	export module opengl {
		export class GLES20 {
			public constructor();
			public static glActiveTexture(param0: number): void;
			public static glAttachShader(param0: number, param1: number): void;
			public static glBindAttribLocation(param0: number, param1: number, param2: string): void;
			public static glBindBuffer(param0: number, param1: number): void;
			public static glBindFramebuffer(param0: number, param1: number): void;
			public static glBindRenderbuffer(param0: number, param1: number): void;
			public static glBindTexture(param0: number, param1: number): void;
			public static glBlendColor(param0: number, param1: number, param2: number, param3: number): void;
			public static glBlendEquation(param0: number): void;
			public static glBlendEquationSeparate(param0: number, param1: number): void;
			public static glBlendFunc(param0: number, param1: number): void;
			public static glBlendFuncSeparate(param0: number, param1: number, param2: number, param3: number): void;
			public static glBufferData(param0: number, param1: number, param2: java.nio.Buffer, param3: number): void;
			public static glBufferSubData(param0: number, param1: number, param2: number, param3: java.nio.Buffer): void;
			public static glCheckFramebufferStatus(param0: number): number;
			public static glClear(param0: number): void;
			public static glClearColor(param0: number, param1: number, param2: number, param3: number): void;
			public static glClearDepthf(param0: number): void;
			public static glClearStencil(param0: number): void;
			public static glColorMask(param0: boolean, param1: boolean, param2: boolean, param3: boolean): void;
			public static glCompileShader(param0: number): void;
			public static glCompressedTexImage2D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: java.nio.Buffer): void;
			public static glCompressedTexSubImage2D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: java.nio.Buffer): void;
			public static glCopyTexImage2D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number): void;
			public static glCopyTexSubImage2D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number): void;
			public static glCreateProgram(): number;
			public static glCreateShader(param0: number): number;
			public static glCullFace(param0: number): void;
			public static glDeleteBuffers(param0: number, param1: native.Array<number>, param2: number): void;
			public static glDeleteBuffers(param0: number, param1: java.nio.IntBuffer): void;
			public static glDeleteFramebuffers(param0: number, param1: native.Array<number>, param2: number): void;
			public static glDeleteFramebuffers(param0: number, param1: java.nio.IntBuffer): void;
			public static glDeleteProgram(param0: number): void;
			public static glDeleteRenderbuffers(param0: number, param1: native.Array<number>, param2: number): void;
			public static glDeleteRenderbuffers(param0: number, param1: java.nio.IntBuffer): void;
			public static glDeleteShader(param0: number): void;
			public static glDeleteTextures(param0: number, param1: native.Array<number>, param2: number): void;
			public static glDeleteTextures(param0: number, param1: java.nio.IntBuffer): void;
			public static glDepthFunc(param0: number): void;
			public static glDepthMask(param0: boolean): void;
			public static glDepthRangef(param0: number, param1: number): void;
			public static glDetachShader(param0: number, param1: number): void;
			public static glDisable(param0: number): void;
			public static glDisableVertexAttribArray(param0: number): void;
			public static glDrawArrays(param0: number, param1: number, param2: number): void;
			public static glDrawElements(param0: number, param1: number, param2: number, param3: number): void;
			public static glDrawElements(param0: number, param1: number, param2: number, param3: java.nio.Buffer): void;
			public static glEnable(param0: number): void;
			public static glEnableVertexAttribArray(param0: number): void;
			public static glFinish(): void;
			public static glFlush(): void;
			public static glFramebufferRenderbuffer(param0: number, param1: number, param2: number, param3: number): void;
			public static glFramebufferTexture2D(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glFrontFace(param0: number): void;
			public static glGenBuffers(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGenBuffers(param0: number, param1: java.nio.IntBuffer): void;
			public static glGenerateMipmap(param0: number): void;
			public static glGenFramebuffers(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGenFramebuffers(param0: number, param1: java.nio.IntBuffer): void;
			public static glGenRenderbuffers(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGenRenderbuffers(param0: number, param1: java.nio.IntBuffer): void;
			public static glGenTextures(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGenTextures(param0: number, param1: java.nio.IntBuffer): void;
			public static glGetActiveAttrib(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number, param5: native.Array<number>, param6: number, param7: native.Array<number>, param8: number, param9: native.Array<number>, param10: number): void;
			public static glGetActiveAttrib(param0: number, param1: number, param2: native.Array<number>, param3: number, param4: native.Array<number>, param5: number): string;
			public static glGetActiveAttrib(param0: number, param1: number, param2: java.nio.IntBuffer, param3: java.nio.IntBuffer): string;
			public static glGetActiveUniform(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number, param5: native.Array<number>, param6: number, param7: native.Array<number>, param8: number, param9: native.Array<number>, param10: number): void;
			public static glGetActiveUniform(param0: number, param1: number, param2: native.Array<number>, param3: number, param4: native.Array<number>, param5: number): string;
			public static glGetActiveUniform(param0: number, param1: number, param2: java.nio.IntBuffer, param3: java.nio.IntBuffer): string;
			public static glGetAttachedShaders(param0: number, param1: number, param2: native.Array<number>, param3: number, param4: native.Array<number>, param5: number): void;
			public static glGetAttachedShaders(param0: number, param1: number, param2: java.nio.IntBuffer, param3: java.nio.IntBuffer): void;
			public static glGetAttribLocation(param0: number, param1: string): number;
			public static glGetBooleanv(param0: number, param1: native.Array<boolean>, param2: number): void;
			public static glGetBooleanv(param0: number, param1: java.nio.IntBuffer): void;
			public static glGetBufferParameteriv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetBufferParameteriv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetError(): number;
			public static glGetFloatv(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGetFloatv(param0: number, param1: java.nio.FloatBuffer): void;
			public static glGetFramebufferAttachmentParameteriv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glGetFramebufferAttachmentParameteriv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer): void;
			public static glGetIntegerv(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGetIntegerv(param0: number, param1: java.nio.IntBuffer): void;
			public static glGetProgramiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetProgramiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetProgramInfoLog(param0: number): string;
			public static glGetRenderbufferParameteriv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetRenderbufferParameteriv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetShaderiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetShaderiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetShaderInfoLog(param0: number): string;
			public static glGetShaderPrecisionFormat(param0: number, param1: number, param2: native.Array<number>, param3: number, param4: native.Array<number>, param5: number): void;
			public static glGetShaderPrecisionFormat(param0: number, param1: number, param2: java.nio.IntBuffer, param3: java.nio.IntBuffer): void;
			public static glGetShaderSource(param0: number, param1: number, param2: native.Array<number>, param3: number, param4: native.Array<number>, param5: number): void;
			public static glGetShaderSource(param0: number): string;
			public static glGetString(param0: number): string;
			public static glGetTexParameterfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetTexParameterfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glGetTexParameteriv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetTexParameteriv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetUniformfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetUniformfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glGetUniformiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetUniformiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetUniformLocation(param0: number, param1: string): number;
			public static glGetVertexAttribfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetVertexAttribfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glGetVertexAttribiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetVertexAttribiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glHint(param0: number, param1: number): void;
			public static glIsBuffer(param0: number): boolean;
			public static glIsEnabled(param0: number): boolean;
			public static glIsFramebuffer(param0: number): boolean;
			public static glIsProgram(param0: number): boolean;
			public static glIsRenderbuffer(param0: number): boolean;
			public static glIsShader(param0: number): boolean;
			public static glIsTexture(param0: number): boolean;
			public static glLineWidth(param0: number): void;
			public static glLinkProgram(param0: number): void;
			public static glPixelStorei(param0: number, param1: number): void;
			public static glPolygonOffset(param0: number, param1: number): void;
			public static glReadPixels(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: java.nio.Buffer): void;
			public static glReleaseShaderCompiler(): void;
			public static glRenderbufferStorage(param0: number, param1: number, param2: number, param3: number): void;
			public static glSampleCoverage(param0: number, param1: boolean): void;
			public static glScissor(param0: number, param1: number, param2: number, param3: number): void;
			public static glShaderBinary(param0: number, param1: native.Array<number>, param2: number, param3: number, param4: java.nio.Buffer, param5: number): void;
			public static glShaderBinary(param0: number, param1: java.nio.IntBuffer, param2: number, param3: java.nio.Buffer, param4: number): void;
			public static glShaderSource(param0: number, param1: string): void;
			public static glStencilFunc(param0: number, param1: number, param2: number): void;
			public static glStencilFuncSeparate(param0: number, param1: number, param2: number, param3: number): void;
			public static glStencilMask(param0: number): void;
			public static glStencilMaskSeparate(param0: number, param1: number): void;
			public static glStencilOp(param0: number, param1: number, param2: number): void;
			public static glStencilOpSeparate(param0: number, param1: number, param2: number, param3: number): void;
			public static glTexImage2D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: java.nio.Buffer): void;
			public static glTexParameterf(param0: number, param1: number, param2: number): void;
			public static glTexParameterfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glTexParameterfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glTexParameteri(param0: number, param1: number, param2: number): void;
			public static glTexParameteriv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glTexParameteriv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glTexSubImage2D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: java.nio.Buffer): void;
			public static glUniform1f(param0: number, param1: number): void;
			public static glUniform1fv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glUniform1fv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glUniform1i(param0: number, param1: number): void;
			public static glUniform1iv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glUniform1iv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glUniform2f(param0: number, param1: number, param2: number): void;
			public static glUniform2fv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glUniform2fv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glUniform2i(param0: number, param1: number, param2: number): void;
			public static glUniform2iv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glUniform2iv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glUniform3f(param0: number, param1: number, param2: number, param3: number): void;
			public static glUniform3fv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glUniform3fv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glUniform3i(param0: number, param1: number, param2: number, param3: number): void;
			public static glUniform3iv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glUniform3iv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glUniform4f(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glUniform4fv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glUniform4fv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glUniform4i(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glUniform4iv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glUniform4iv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glUniformMatrix2fv(param0: number, param1: number, param2: boolean, param3: native.Array<number>, param4: number): void;
			public static glUniformMatrix2fv(param0: number, param1: number, param2: boolean, param3: java.nio.FloatBuffer): void;
			public static glUniformMatrix3fv(param0: number, param1: number, param2: boolean, param3: native.Array<number>, param4: number): void;
			public static glUniformMatrix3fv(param0: number, param1: number, param2: boolean, param3: java.nio.FloatBuffer): void;
			public static glUniformMatrix4fv(param0: number, param1: number, param2: boolean, param3: native.Array<number>, param4: number): void;
			public static glUniformMatrix4fv(param0: number, param1: number, param2: boolean, param3: java.nio.FloatBuffer): void;
			public static glUseProgram(param0: number): void;
			public static glValidateProgram(param0: number): void;
			public static glVertexAttrib1f(param0: number, param1: number): void;
			public static glVertexAttrib1fv(param0: number, param1: native.Array<number>, param2: number): void;
			public static glVertexAttrib1fv(param0: number, param1: java.nio.FloatBuffer): void;
			public static glVertexAttrib2f(param0: number, param1: number, param2: number): void;
			public static glVertexAttrib2fv(param0: number, param1: native.Array<number>, param2: number): void;
			public static glVertexAttrib2fv(param0: number, param1: java.nio.FloatBuffer): void;
			public static glVertexAttrib3f(param0: number, param1: number, param2: number, param3: number): void;
			public static glVertexAttrib3fv(param0: number, param1: native.Array<number>, param2: number): void;
			public static glVertexAttrib3fv(param0: number, param1: java.nio.FloatBuffer): void;
			public static glVertexAttrib4f(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glVertexAttrib4fv(param0: number, param1: native.Array<number>, param2: number): void;
			public static glVertexAttrib4fv(param0: number, param1: java.nio.FloatBuffer): void;
			public static glVertexAttribPointer(param0: number, param1: number, param2: number, param3: boolean, param4: number, param5: number): void;
			public static glVertexAttribPointer(param0: number, param1: number, param2: number, param3: boolean, param4: number, param5: java.nio.Buffer): void;
			public static glViewport(param0: number, param1: number, param2: number, param3: number): void;
			public static GL_ACTIVE_ATTRIBUTES: number;
			public static GL_ACTIVE_ATTRIBUTE_MAX_LENGTH: number;
			public static GL_ACTIVE_TEXTURE: number;
			public static GL_ACTIVE_UNIFORMS: number;
			public static GL_ACTIVE_UNIFORM_MAX_LENGTH: number;
			public static GL_ALIASED_LINE_WIDTH_RANGE: number;
			public static GL_ALIASED_POINT_SIZE_RANGE: number;
			public static GL_ALPHA: number;
			public static GL_ALPHA_BITS: number;
			public static GL_ALWAYS: number;
			public static GL_ARRAY_BUFFER: number;
			public static GL_ARRAY_BUFFER_BINDING: number;
			public static GL_ATTACHED_SHADERS: number;
			public static GL_BACK: number;
			public static GL_BLEND: number;
			public static GL_BLEND_COLOR: number;
			public static GL_BLEND_DST_ALPHA: number;
			public static GL_BLEND_DST_RGB: number;
			public static GL_BLEND_EQUATION: number;
			public static GL_BLEND_EQUATION_ALPHA: number;
			public static GL_BLEND_EQUATION_RGB: number;
			public static GL_BLEND_SRC_ALPHA: number;
			public static GL_BLEND_SRC_RGB: number;
			public static GL_BLUE_BITS: number;
			public static GL_BOOL: number;
			public static GL_BOOL_VEC2: number;
			public static GL_BOOL_VEC3: number;
			public static GL_BOOL_VEC4: number;
			public static GL_BUFFER_SIZE: number;
			public static GL_BUFFER_USAGE: number;
			public static GL_BYTE: number;
			public static GL_CCW: number;
			public static GL_CLAMP_TO_EDGE: number;
			public static GL_COLOR_ATTACHMENT0: number;
			public static GL_COLOR_BUFFER_BIT: number;
			public static GL_COLOR_CLEAR_VALUE: number;
			public static GL_COLOR_WRITEMASK: number;
			public static GL_COMPILE_STATUS: number;
			public static GL_COMPRESSED_TEXTURE_FORMATS: number;
			public static GL_CONSTANT_ALPHA: number;
			public static GL_CONSTANT_COLOR: number;
			public static GL_CULL_FACE: number;
			public static GL_CULL_FACE_MODE: number;
			public static GL_CURRENT_PROGRAM: number;
			public static GL_CURRENT_VERTEX_ATTRIB: number;
			public static GL_CW: number;
			public static GL_DECR: number;
			public static GL_DECR_WRAP: number;
			public static GL_DELETE_STATUS: number;
			public static GL_DEPTH_ATTACHMENT: number;
			public static GL_DEPTH_BITS: number;
			public static GL_DEPTH_BUFFER_BIT: number;
			public static GL_DEPTH_CLEAR_VALUE: number;
			public static GL_DEPTH_COMPONENT: number;
			public static GL_DEPTH_COMPONENT16: number;
			public static GL_DEPTH_FUNC: number;
			public static GL_DEPTH_RANGE: number;
			public static GL_DEPTH_TEST: number;
			public static GL_DEPTH_WRITEMASK: number;
			public static GL_DITHER: number;
			public static GL_DONT_CARE: number;
			public static GL_DST_ALPHA: number;
			public static GL_DST_COLOR: number;
			public static GL_DYNAMIC_DRAW: number;
			public static GL_ELEMENT_ARRAY_BUFFER: number;
			public static GL_ELEMENT_ARRAY_BUFFER_BINDING: number;
			public static GL_EQUAL: number;
			public static GL_EXTENSIONS: number;
			public static GL_FALSE: number;
			public static GL_FASTEST: number;
			public static GL_FIXED: number;
			public static GL_FLOAT: number;
			public static GL_FLOAT_MAT2: number;
			public static GL_FLOAT_MAT3: number;
			public static GL_FLOAT_MAT4: number;
			public static GL_FLOAT_VEC2: number;
			public static GL_FLOAT_VEC3: number;
			public static GL_FLOAT_VEC4: number;
			public static GL_FRAGMENT_SHADER: number;
			public static GL_FRAMEBUFFER: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL: number;
			public static GL_FRAMEBUFFER_BINDING: number;
			public static GL_FRAMEBUFFER_COMPLETE: number;
			public static GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT: number;
			public static GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS: number;
			public static GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: number;
			public static GL_FRAMEBUFFER_UNSUPPORTED: number;
			public static GL_FRONT: number;
			public static GL_FRONT_AND_BACK: number;
			public static GL_FRONT_FACE: number;
			public static GL_FUNC_ADD: number;
			public static GL_FUNC_REVERSE_SUBTRACT: number;
			public static GL_FUNC_SUBTRACT: number;
			public static GL_GENERATE_MIPMAP_HINT: number;
			public static GL_GEQUAL: number;
			public static GL_GREATER: number;
			public static GL_GREEN_BITS: number;
			public static GL_HIGH_FLOAT: number;
			public static GL_HIGH_INT: number;
			public static GL_IMPLEMENTATION_COLOR_READ_FORMAT: number;
			public static GL_IMPLEMENTATION_COLOR_READ_TYPE: number;
			public static GL_INCR: number;
			public static GL_INCR_WRAP: number;
			public static GL_INFO_LOG_LENGTH: number;
			public static GL_INT: number;
			public static GL_INT_VEC2: number;
			public static GL_INT_VEC3: number;
			public static GL_INT_VEC4: number;
			public static GL_INVALID_ENUM: number;
			public static GL_INVALID_FRAMEBUFFER_OPERATION: number;
			public static GL_INVALID_OPERATION: number;
			public static GL_INVALID_VALUE: number;
			public static GL_INVERT: number;
			public static GL_KEEP: number;
			public static GL_LEQUAL: number;
			public static GL_LESS: number;
			public static GL_LINEAR: number;
			public static GL_LINEAR_MIPMAP_LINEAR: number;
			public static GL_LINEAR_MIPMAP_NEAREST: number;
			public static GL_LINES: number;
			public static GL_LINE_LOOP: number;
			public static GL_LINE_STRIP: number;
			public static GL_LINE_WIDTH: number;
			public static GL_LINK_STATUS: number;
			public static GL_LOW_FLOAT: number;
			public static GL_LOW_INT: number;
			public static GL_LUMINANCE: number;
			public static GL_LUMINANCE_ALPHA: number;
			public static GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: number;
			public static GL_MAX_CUBE_MAP_TEXTURE_SIZE: number;
			public static GL_MAX_FRAGMENT_UNIFORM_VECTORS: number;
			public static GL_MAX_RENDERBUFFER_SIZE: number;
			public static GL_MAX_TEXTURE_IMAGE_UNITS: number;
			public static GL_MAX_TEXTURE_SIZE: number;
			public static GL_MAX_VARYING_VECTORS: number;
			public static GL_MAX_VERTEX_ATTRIBS: number;
			public static GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS: number;
			public static GL_MAX_VERTEX_UNIFORM_VECTORS: number;
			public static GL_MAX_VIEWPORT_DIMS: number;
			public static GL_MEDIUM_FLOAT: number;
			public static GL_MEDIUM_INT: number;
			public static GL_MIRRORED_REPEAT: number;
			public static GL_NEAREST: number;
			public static GL_NEAREST_MIPMAP_LINEAR: number;
			public static GL_NEAREST_MIPMAP_NEAREST: number;
			public static GL_NEVER: number;
			public static GL_NICEST: number;
			public static GL_NONE: number;
			public static GL_NOTEQUAL: number;
			public static GL_NO_ERROR: number;
			public static GL_NUM_COMPRESSED_TEXTURE_FORMATS: number;
			public static GL_NUM_SHADER_BINARY_FORMATS: number;
			public static GL_ONE: number;
			public static GL_ONE_MINUS_CONSTANT_ALPHA: number;
			public static GL_ONE_MINUS_CONSTANT_COLOR: number;
			public static GL_ONE_MINUS_DST_ALPHA: number;
			public static GL_ONE_MINUS_DST_COLOR: number;
			public static GL_ONE_MINUS_SRC_ALPHA: number;
			public static GL_ONE_MINUS_SRC_COLOR: number;
			public static GL_OUT_OF_MEMORY: number;
			public static GL_PACK_ALIGNMENT: number;
			public static GL_POINTS: number;
			public static GL_POLYGON_OFFSET_FACTOR: number;
			public static GL_POLYGON_OFFSET_FILL: number;
			public static GL_POLYGON_OFFSET_UNITS: number;
			public static GL_RED_BITS: number;
			public static GL_RENDERBUFFER: number;
			public static GL_RENDERBUFFER_ALPHA_SIZE: number;
			public static GL_RENDERBUFFER_BINDING: number;
			public static GL_RENDERBUFFER_BLUE_SIZE: number;
			public static GL_RENDERBUFFER_DEPTH_SIZE: number;
			public static GL_RENDERBUFFER_GREEN_SIZE: number;
			public static GL_RENDERBUFFER_HEIGHT: number;
			public static GL_RENDERBUFFER_INTERNAL_FORMAT: number;
			public static GL_RENDERBUFFER_RED_SIZE: number;
			public static GL_RENDERBUFFER_STENCIL_SIZE: number;
			public static GL_RENDERBUFFER_WIDTH: number;
			public static GL_RENDERER: number;
			public static GL_REPEAT: number;
			public static GL_REPLACE: number;
			public static GL_RGB: number;
			public static GL_RGB565: number;
			public static GL_RGB5_A1: number;
			public static GL_RGBA: number;
			public static GL_RGBA4: number;
			public static GL_SAMPLER_2D: number;
			public static GL_SAMPLER_CUBE: number;
			public static GL_SAMPLES: number;
			public static GL_SAMPLE_ALPHA_TO_COVERAGE: number;
			public static GL_SAMPLE_BUFFERS: number;
			public static GL_SAMPLE_COVERAGE: number;
			public static GL_SAMPLE_COVERAGE_INVERT: number;
			public static GL_SAMPLE_COVERAGE_VALUE: number;
			public static GL_SCISSOR_BOX: number;
			public static GL_SCISSOR_TEST: number;
			public static GL_SHADER_BINARY_FORMATS: number;
			public static GL_SHADER_COMPILER: number;
			public static GL_SHADER_SOURCE_LENGTH: number;
			public static GL_SHADER_TYPE: number;
			public static GL_SHADING_LANGUAGE_VERSION: number;
			public static GL_SHORT: number;
			public static GL_SRC_ALPHA: number;
			public static GL_SRC_ALPHA_SATURATE: number;
			public static GL_SRC_COLOR: number;
			public static GL_STATIC_DRAW: number;
			public static GL_STENCIL_ATTACHMENT: number;
			public static GL_STENCIL_BACK_FAIL: number;
			public static GL_STENCIL_BACK_FUNC: number;
			public static GL_STENCIL_BACK_PASS_DEPTH_FAIL: number;
			public static GL_STENCIL_BACK_PASS_DEPTH_PASS: number;
			public static GL_STENCIL_BACK_REF: number;
			public static GL_STENCIL_BACK_VALUE_MASK: number;
			public static GL_STENCIL_BACK_WRITEMASK: number;
			public static GL_STENCIL_BITS: number;
			public static GL_STENCIL_BUFFER_BIT: number;
			public static GL_STENCIL_CLEAR_VALUE: number;
			public static GL_STENCIL_FAIL: number;
			public static GL_STENCIL_FUNC: number;
			public static GL_STENCIL_INDEX: number;
			public static GL_STENCIL_INDEX8: number;
			public static GL_STENCIL_PASS_DEPTH_FAIL: number;
			public static GL_STENCIL_PASS_DEPTH_PASS: number;
			public static GL_STENCIL_REF: number;
			public static GL_STENCIL_TEST: number;
			public static GL_STENCIL_VALUE_MASK: number;
			public static GL_STENCIL_WRITEMASK: number;
			public static GL_STREAM_DRAW: number;
			public static GL_SUBPIXEL_BITS: number;
			public static GL_TEXTURE: number;
			public static GL_TEXTURE0: number;
			public static GL_TEXTURE1: number;
			public static GL_TEXTURE10: number;
			public static GL_TEXTURE11: number;
			public static GL_TEXTURE12: number;
			public static GL_TEXTURE13: number;
			public static GL_TEXTURE14: number;
			public static GL_TEXTURE15: number;
			public static GL_TEXTURE16: number;
			public static GL_TEXTURE17: number;
			public static GL_TEXTURE18: number;
			public static GL_TEXTURE19: number;
			public static GL_TEXTURE2: number;
			public static GL_TEXTURE20: number;
			public static GL_TEXTURE21: number;
			public static GL_TEXTURE22: number;
			public static GL_TEXTURE23: number;
			public static GL_TEXTURE24: number;
			public static GL_TEXTURE25: number;
			public static GL_TEXTURE26: number;
			public static GL_TEXTURE27: number;
			public static GL_TEXTURE28: number;
			public static GL_TEXTURE29: number;
			public static GL_TEXTURE3: number;
			public static GL_TEXTURE30: number;
			public static GL_TEXTURE31: number;
			public static GL_TEXTURE4: number;
			public static GL_TEXTURE5: number;
			public static GL_TEXTURE6: number;
			public static GL_TEXTURE7: number;
			public static GL_TEXTURE8: number;
			public static GL_TEXTURE9: number;
			public static GL_TEXTURE_2D: number;
			public static GL_TEXTURE_BINDING_2D: number;
			public static GL_TEXTURE_BINDING_CUBE_MAP: number;
			public static GL_TEXTURE_CUBE_MAP: number;
			public static GL_TEXTURE_CUBE_MAP_NEGATIVE_X: number;
			public static GL_TEXTURE_CUBE_MAP_NEGATIVE_Y: number;
			public static GL_TEXTURE_CUBE_MAP_NEGATIVE_Z: number;
			public static GL_TEXTURE_CUBE_MAP_POSITIVE_X: number;
			public static GL_TEXTURE_CUBE_MAP_POSITIVE_Y: number;
			public static GL_TEXTURE_CUBE_MAP_POSITIVE_Z: number;
			public static GL_TEXTURE_MAG_FILTER: number;
			public static GL_TEXTURE_MIN_FILTER: number;
			public static GL_TEXTURE_WRAP_S: number;
			public static GL_TEXTURE_WRAP_T: number;
			public static GL_TRIANGLES: number;
			public static GL_TRIANGLE_FAN: number;
			public static GL_TRIANGLE_STRIP: number;
			public static GL_TRUE: number;
			public static GL_UNPACK_ALIGNMENT: number;
			public static GL_UNSIGNED_BYTE: number;
			public static GL_UNSIGNED_INT: number;
			public static GL_UNSIGNED_SHORT: number;
			public static GL_UNSIGNED_SHORT_4_4_4_4: number;
			public static GL_UNSIGNED_SHORT_5_5_5_1: number;
			public static GL_UNSIGNED_SHORT_5_6_5: number;
			public static GL_VALIDATE_STATUS: number;
			public static GL_VENDOR: number;
			public static GL_VERSION: number;
			public static GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING: number;
			public static GL_VERTEX_ATTRIB_ARRAY_ENABLED: number;
			public static GL_VERTEX_ATTRIB_ARRAY_NORMALIZED: number;
			public static GL_VERTEX_ATTRIB_ARRAY_POINTER: number;
			public static GL_VERTEX_ATTRIB_ARRAY_SIZE: number;
			public static GL_VERTEX_ATTRIB_ARRAY_STRIDE: number;
			public static GL_VERTEX_ATTRIB_ARRAY_TYPE: number;
			public static GL_VERTEX_SHADER: number;
			public static GL_VIEWPORT: number;
			public static GL_ZERO: number;
		}
	}
}
