/// <reference path="./_helpers.d.ts" />
/// <reference path="./java.lang.String.d.ts" />
/// <reference path="./java.nio.Buffer.d.ts" />
/// <reference path="./java.nio.FloatBuffer.d.ts" />
/// <reference path="./java.nio.IntBuffer.d.ts" />
/// <reference path="./java.nio.LongBuffer.d.ts" />

declare module android {
	export module opengl {
		export class GLES30 {
			public constructor();
			public static glReadBuffer(param0: number): void;
			public static glDrawRangeElements(param0: number, param1: number, param2: number, param3: number, param4: number, param5: java.nio.Buffer): void;
			public static glDrawRangeElements(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number): void;
			public static glTexImage3D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: number, param9: java.nio.Buffer): void;
			public static glTexImage3D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: number, param9: number): void;
			public static glTexSubImage3D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: number, param9: number, param10: java.nio.Buffer): void;
			public static glTexSubImage3D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: number, param9: number, param10: number): void;
			public static glCopyTexSubImage3D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: number): void;
			public static glCompressedTexImage3D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: java.nio.Buffer): void;
			public static glCompressedTexImage3D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: number): void;
			public static glCompressedTexSubImage3D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: number, param9: number, param10: java.nio.Buffer): void;
			public static glCompressedTexSubImage3D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: number, param9: number, param10: number): void;
			public static glGenQueries(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGenQueries(param0: number, param1: java.nio.IntBuffer): void;
			public static glDeleteQueries(param0: number, param1: native.Array<number>, param2: number): void;
			public static glDeleteQueries(param0: number, param1: java.nio.IntBuffer): void;
			public static glIsQuery(param0: number): boolean;
			public static glBeginQuery(param0: number, param1: number): void;
			public static glEndQuery(param0: number): void;
			public static glGetQueryiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetQueryiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetQueryObjectuiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetQueryObjectuiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glUnmapBuffer(param0: number): boolean;
			public static glGetBufferPointerv(param0: number, param1: number): java.nio.Buffer;
			public static glDrawBuffers(param0: number, param1: native.Array<number>, param2: number): void;
			public static glDrawBuffers(param0: number, param1: java.nio.IntBuffer): void;
			public static glUniformMatrix2x3fv(param0: number, param1: number, param2: boolean, param3: native.Array<number>, param4: number): void;
			public static glUniformMatrix2x3fv(param0: number, param1: number, param2: boolean, param3: java.nio.FloatBuffer): void;
			public static glUniformMatrix3x2fv(param0: number, param1: number, param2: boolean, param3: native.Array<number>, param4: number): void;
			public static glUniformMatrix3x2fv(param0: number, param1: number, param2: boolean, param3: java.nio.FloatBuffer): void;
			public static glUniformMatrix2x4fv(param0: number, param1: number, param2: boolean, param3: native.Array<number>, param4: number): void;
			public static glUniformMatrix2x4fv(param0: number, param1: number, param2: boolean, param3: java.nio.FloatBuffer): void;
			public static glUniformMatrix4x2fv(param0: number, param1: number, param2: boolean, param3: native.Array<number>, param4: number): void;
			public static glUniformMatrix4x2fv(param0: number, param1: number, param2: boolean, param3: java.nio.FloatBuffer): void;
			public static glUniformMatrix3x4fv(param0: number, param1: number, param2: boolean, param3: native.Array<number>, param4: number): void;
			public static glUniformMatrix3x4fv(param0: number, param1: number, param2: boolean, param3: java.nio.FloatBuffer): void;
			public static glUniformMatrix4x3fv(param0: number, param1: number, param2: boolean, param3: native.Array<number>, param4: number): void;
			public static glUniformMatrix4x3fv(param0: number, param1: number, param2: boolean, param3: java.nio.FloatBuffer): void;
			public static glBlitFramebuffer(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: number, param9: number): void;
			public static glRenderbufferStorageMultisample(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glFramebufferTextureLayer(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glMapBufferRange(param0: number, param1: number, param2: number, param3: number): java.nio.Buffer;
			public static glFlushMappedBufferRange(param0: number, param1: number, param2: number): void;
			public static glBindVertexArray(param0: number): void;
			public static glDeleteVertexArrays(param0: number, param1: native.Array<number>, param2: number): void;
			public static glDeleteVertexArrays(param0: number, param1: java.nio.IntBuffer): void;
			public static glGenVertexArrays(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGenVertexArrays(param0: number, param1: java.nio.IntBuffer): void;
			public static glIsVertexArray(param0: number): boolean;
			public static glGetIntegeri_v(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetIntegeri_v(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glBeginTransformFeedback(param0: number): void;
			public static glEndTransformFeedback(): void;
			public static glBindBufferRange(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glBindBufferBase(param0: number, param1: number, param2: number): void;
			public static glTransformFeedbackVaryings(param0: number, param1: native.Array<string>, param2: number): void;
			public static glGetTransformFeedbackVarying(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number, param5: native.Array<number>, param6: number, param7: native.Array<number>, param8: number, param9: native.Array<number>, param10: number): void;
			public static glGetTransformFeedbackVarying(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer, param4: java.nio.IntBuffer, param5: java.nio.IntBuffer, param6: number): void;
			public static glGetTransformFeedbackVarying(param0: number, param1: number, param2: native.Array<number>, param3: number, param4: native.Array<number>, param5: number): string;
			public static glGetTransformFeedbackVarying(param0: number, param1: number, param2: java.nio.IntBuffer, param3: java.nio.IntBuffer): string;
			public static glVertexAttribIPointer(param0: number, param1: number, param2: number, param3: number, param4: java.nio.Buffer): void;
			public static glVertexAttribIPointer(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glGetVertexAttribIiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetVertexAttribIiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetVertexAttribIuiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetVertexAttribIuiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glVertexAttribI4i(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glVertexAttribI4ui(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glVertexAttribI4iv(param0: number, param1: native.Array<number>, param2: number): void;
			public static glVertexAttribI4iv(param0: number, param1: java.nio.IntBuffer): void;
			public static glVertexAttribI4uiv(param0: number, param1: native.Array<number>, param2: number): void;
			public static glVertexAttribI4uiv(param0: number, param1: java.nio.IntBuffer): void;
			public static glGetUniformuiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetUniformuiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetFragDataLocation(param0: number, param1: string): number;
			public static glUniform1ui(param0: number, param1: number): void;
			public static glUniform2ui(param0: number, param1: number, param2: number): void;
			public static glUniform3ui(param0: number, param1: number, param2: number, param3: number): void;
			public static glUniform4ui(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glUniform1uiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glUniform1uiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glUniform2uiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glUniform2uiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glUniform3uiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glUniform3uiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glUniform4uiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glUniform4uiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glClearBufferiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glClearBufferiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glClearBufferuiv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glClearBufferuiv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glClearBufferfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glClearBufferfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glClearBufferfi(param0: number, param1: number, param2: number, param3: number): void;
			public static glGetStringi(param0: number, param1: number): string;
			public static glCopyBufferSubData(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glGetUniformIndices(param0: number, param1: native.Array<string>, param2: native.Array<number>, param3: number): void;
			public static glGetUniformIndices(param0: number, param1: native.Array<string>, param2: java.nio.IntBuffer): void;
			public static glGetActiveUniformsiv(param0: number, param1: number, param2: native.Array<number>, param3: number, param4: number, param5: native.Array<number>, param6: number): void;
			public static glGetActiveUniformsiv(param0: number, param1: number, param2: java.nio.IntBuffer, param3: number, param4: java.nio.IntBuffer): void;
			public static glGetUniformBlockIndex(param0: number, param1: string): number;
			public static glGetActiveUniformBlockiv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number): void;
			public static glGetActiveUniformBlockiv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer): void;
			public static glGetActiveUniformBlockName(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number, param5: native.Array<number>, param6: number): void;
			public static glGetActiveUniformBlockName(param0: number, param1: number, param2: java.nio.Buffer, param3: java.nio.Buffer): void;
			public static glGetActiveUniformBlockName(param0: number, param1: number): string;
			public static glUniformBlockBinding(param0: number, param1: number, param2: number): void;
			public static glDrawArraysInstanced(param0: number, param1: number, param2: number, param3: number): void;
			public static glDrawElementsInstanced(param0: number, param1: number, param2: number, param3: java.nio.Buffer, param4: number): void;
			public static glDrawElementsInstanced(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glFenceSync(param0: number, param1: number): number;
			public static glIsSync(param0: number): boolean;
			public static glDeleteSync(param0: number): void;
			public static glClientWaitSync(param0: number, param1: number, param2: number): number;
			public static glWaitSync(param0: number, param1: number, param2: number): void;
			public static glGetInteger64v(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGetInteger64v(param0: number, param1: java.nio.LongBuffer): void;
			public static glGetSynciv(param0: number, param1: number, param2: number, param3: native.Array<number>, param4: number, param5: native.Array<number>, param6: number): void;
			public static glGetSynciv(param0: number, param1: number, param2: number, param3: java.nio.IntBuffer, param4: java.nio.IntBuffer): void;
			public static glGetInteger64i_v(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetInteger64i_v(param0: number, param1: number, param2: java.nio.LongBuffer): void;
			public static glGetBufferParameteri64v(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetBufferParameteri64v(param0: number, param1: number, param2: java.nio.LongBuffer): void;
			public static glGenSamplers(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGenSamplers(param0: number, param1: java.nio.IntBuffer): void;
			public static glDeleteSamplers(param0: number, param1: native.Array<number>, param2: number): void;
			public static glDeleteSamplers(param0: number, param1: java.nio.IntBuffer): void;
			public static glIsSampler(param0: number): boolean;
			public static glBindSampler(param0: number, param1: number): void;
			public static glSamplerParameteri(param0: number, param1: number, param2: number): void;
			public static glSamplerParameteriv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glSamplerParameteriv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glSamplerParameterf(param0: number, param1: number, param2: number): void;
			public static glSamplerParameterfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glSamplerParameterfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glGetSamplerParameteriv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetSamplerParameteriv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glGetSamplerParameterfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glGetSamplerParameterfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
			public static glVertexAttribDivisor(param0: number, param1: number): void;
			public static glBindTransformFeedback(param0: number, param1: number): void;
			public static glDeleteTransformFeedbacks(param0: number, param1: native.Array<number>, param2: number): void;
			public static glDeleteTransformFeedbacks(param0: number, param1: java.nio.IntBuffer): void;
			public static glGenTransformFeedbacks(param0: number, param1: native.Array<number>, param2: number): void;
			public static glGenTransformFeedbacks(param0: number, param1: java.nio.IntBuffer): void;
			public static glIsTransformFeedback(param0: number): boolean;
			public static glPauseTransformFeedback(): void;
			public static glResumeTransformFeedback(): void;
			public static glGetProgramBinary(param0: number, param1: number, param2: native.Array<number>, param3: number, param4: native.Array<number>, param5: number, param6: java.nio.Buffer): void;
			public static glGetProgramBinary(param0: number, param1: number, param2: java.nio.IntBuffer, param3: java.nio.IntBuffer, param4: java.nio.Buffer): void;
			public static glProgramBinary(param0: number, param1: number, param2: java.nio.Buffer, param3: number): void;
			public static glProgramParameteri(param0: number, param1: number, param2: number): void;
			public static glInvalidateFramebuffer(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
			public static glInvalidateFramebuffer(param0: number, param1: number, param2: java.nio.IntBuffer): void;
			public static glInvalidateSubFramebuffer(param0: number, param1: number, param2: native.Array<number>, param3: number, param4: number, param5: number, param6: number, param7: number): void;
			public static glInvalidateSubFramebuffer(param0: number, param1: number, param2: java.nio.IntBuffer, param3: number, param4: number, param5: number, param6: number): void;
			public static glTexStorage2D(param0: number, param1: number, param2: number, param3: number, param4: number): void;
			public static glTexStorage3D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number): void;
			public static glGetInternalformativ(param0: number, param1: number, param2: number, param3: number, param4: native.Array<number>, param5: number): void;
			public static glGetInternalformativ(param0: number, param1: number, param2: number, param3: number, param4: java.nio.IntBuffer): void;
			public static GL_ACTIVE_UNIFORM_BLOCKS: number;
			public static GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH: number;
			public static GL_ALREADY_SIGNALED: number;
			public static GL_ANY_SAMPLES_PASSED: number;
			public static GL_ANY_SAMPLES_PASSED_CONSERVATIVE: number;
			public static GL_BLUE: number;
			public static GL_BUFFER_ACCESS_FLAGS: number;
			public static GL_BUFFER_MAPPED: number;
			public static GL_BUFFER_MAP_LENGTH: number;
			public static GL_BUFFER_MAP_OFFSET: number;
			public static GL_BUFFER_MAP_POINTER: number;
			public static GL_COLOR: number;
			public static GL_COLOR_ATTACHMENT1: number;
			public static GL_COLOR_ATTACHMENT10: number;
			public static GL_COLOR_ATTACHMENT11: number;
			public static GL_COLOR_ATTACHMENT12: number;
			public static GL_COLOR_ATTACHMENT13: number;
			public static GL_COLOR_ATTACHMENT14: number;
			public static GL_COLOR_ATTACHMENT15: number;
			public static GL_COLOR_ATTACHMENT2: number;
			public static GL_COLOR_ATTACHMENT3: number;
			public static GL_COLOR_ATTACHMENT4: number;
			public static GL_COLOR_ATTACHMENT5: number;
			public static GL_COLOR_ATTACHMENT6: number;
			public static GL_COLOR_ATTACHMENT7: number;
			public static GL_COLOR_ATTACHMENT8: number;
			public static GL_COLOR_ATTACHMENT9: number;
			public static GL_COMPARE_REF_TO_TEXTURE: number;
			public static GL_COMPRESSED_R11_EAC: number;
			public static GL_COMPRESSED_RG11_EAC: number;
			public static GL_COMPRESSED_RGB8_ETC2: number;
			public static GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2: number;
			public static GL_COMPRESSED_RGBA8_ETC2_EAC: number;
			public static GL_COMPRESSED_SIGNED_R11_EAC: number;
			public static GL_COMPRESSED_SIGNED_RG11_EAC: number;
			public static GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC: number;
			public static GL_COMPRESSED_SRGB8_ETC2: number;
			public static GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2: number;
			public static GL_CONDITION_SATISFIED: number;
			public static GL_COPY_READ_BUFFER: number;
			public static GL_COPY_READ_BUFFER_BINDING: number;
			public static GL_COPY_WRITE_BUFFER: number;
			public static GL_COPY_WRITE_BUFFER_BINDING: number;
			public static GL_CURRENT_QUERY: number;
			public static GL_DEPTH: number;
			public static GL_DEPTH24_STENCIL8: number;
			public static GL_DEPTH32F_STENCIL8: number;
			public static GL_DEPTH_COMPONENT24: number;
			public static GL_DEPTH_COMPONENT32F: number;
			public static GL_DEPTH_STENCIL: number;
			public static GL_DEPTH_STENCIL_ATTACHMENT: number;
			public static GL_DRAW_BUFFER0: number;
			public static GL_DRAW_BUFFER1: number;
			public static GL_DRAW_BUFFER10: number;
			public static GL_DRAW_BUFFER11: number;
			public static GL_DRAW_BUFFER12: number;
			public static GL_DRAW_BUFFER13: number;
			public static GL_DRAW_BUFFER14: number;
			public static GL_DRAW_BUFFER15: number;
			public static GL_DRAW_BUFFER2: number;
			public static GL_DRAW_BUFFER3: number;
			public static GL_DRAW_BUFFER4: number;
			public static GL_DRAW_BUFFER5: number;
			public static GL_DRAW_BUFFER6: number;
			public static GL_DRAW_BUFFER7: number;
			public static GL_DRAW_BUFFER8: number;
			public static GL_DRAW_BUFFER9: number;
			public static GL_DRAW_FRAMEBUFFER: number;
			public static GL_DRAW_FRAMEBUFFER_BINDING: number;
			public static GL_DYNAMIC_COPY: number;
			public static GL_DYNAMIC_READ: number;
			public static GL_FLOAT_32_UNSIGNED_INT_24_8_REV: number;
			public static GL_FLOAT_MAT2x3: number;
			public static GL_FLOAT_MAT2x4: number;
			public static GL_FLOAT_MAT3x2: number;
			public static GL_FLOAT_MAT3x4: number;
			public static GL_FLOAT_MAT4x2: number;
			public static GL_FLOAT_MAT4x3: number;
			public static GL_FRAGMENT_SHADER_DERIVATIVE_HINT: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE: number;
			public static GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER: number;
			public static GL_FRAMEBUFFER_DEFAULT: number;
			public static GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE: number;
			public static GL_FRAMEBUFFER_UNDEFINED: number;
			public static GL_GREEN: number;
			public static GL_HALF_FLOAT: number;
			public static GL_INTERLEAVED_ATTRIBS: number;
			public static GL_INT_2_10_10_10_REV: number;
			public static GL_INT_SAMPLER_2D: number;
			public static GL_INT_SAMPLER_2D_ARRAY: number;
			public static GL_INT_SAMPLER_3D: number;
			public static GL_INT_SAMPLER_CUBE: number;
			public static GL_INVALID_INDEX: number;
			public static GL_MAJOR_VERSION: number;
			public static GL_MAP_FLUSH_EXPLICIT_BIT: number;
			public static GL_MAP_INVALIDATE_BUFFER_BIT: number;
			public static GL_MAP_INVALIDATE_RANGE_BIT: number;
			public static GL_MAP_READ_BIT: number;
			public static GL_MAP_UNSYNCHRONIZED_BIT: number;
			public static GL_MAP_WRITE_BIT: number;
			public static GL_MAX: number;
			public static GL_MAX_3D_TEXTURE_SIZE: number;
			public static GL_MAX_ARRAY_TEXTURE_LAYERS: number;
			public static GL_MAX_COLOR_ATTACHMENTS: number;
			public static GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS: number;
			public static GL_MAX_COMBINED_UNIFORM_BLOCKS: number;
			public static GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS: number;
			public static GL_MAX_DRAW_BUFFERS: number;
			public static GL_MAX_ELEMENTS_INDICES: number;
			public static GL_MAX_ELEMENTS_VERTICES: number;
			public static GL_MAX_ELEMENT_INDEX: number;
			public static GL_MAX_FRAGMENT_INPUT_COMPONENTS: number;
			public static GL_MAX_FRAGMENT_UNIFORM_BLOCKS: number;
			public static GL_MAX_FRAGMENT_UNIFORM_COMPONENTS: number;
			public static GL_MAX_PROGRAM_TEXEL_OFFSET: number;
			public static GL_MAX_SAMPLES: number;
			public static GL_MAX_SERVER_WAIT_TIMEOUT: number;
			public static GL_MAX_TEXTURE_LOD_BIAS: number;
			public static GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS: number;
			public static GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS: number;
			public static GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS: number;
			public static GL_MAX_UNIFORM_BLOCK_SIZE: number;
			public static GL_MAX_UNIFORM_BUFFER_BINDINGS: number;
			public static GL_MAX_VARYING_COMPONENTS: number;
			public static GL_MAX_VERTEX_OUTPUT_COMPONENTS: number;
			public static GL_MAX_VERTEX_UNIFORM_BLOCKS: number;
			public static GL_MAX_VERTEX_UNIFORM_COMPONENTS: number;
			public static GL_MIN: number;
			public static GL_MINOR_VERSION: number;
			public static GL_MIN_PROGRAM_TEXEL_OFFSET: number;
			public static GL_NUM_EXTENSIONS: number;
			public static GL_NUM_PROGRAM_BINARY_FORMATS: number;
			public static GL_NUM_SAMPLE_COUNTS: number;
			public static GL_OBJECT_TYPE: number;
			public static GL_PACK_ROW_LENGTH: number;
			public static GL_PACK_SKIP_PIXELS: number;
			public static GL_PACK_SKIP_ROWS: number;
			public static GL_PIXEL_PACK_BUFFER: number;
			public static GL_PIXEL_PACK_BUFFER_BINDING: number;
			public static GL_PIXEL_UNPACK_BUFFER: number;
			public static GL_PIXEL_UNPACK_BUFFER_BINDING: number;
			public static GL_PRIMITIVE_RESTART_FIXED_INDEX: number;
			public static GL_PROGRAM_BINARY_FORMATS: number;
			public static GL_PROGRAM_BINARY_LENGTH: number;
			public static GL_PROGRAM_BINARY_RETRIEVABLE_HINT: number;
			public static GL_QUERY_RESULT: number;
			public static GL_QUERY_RESULT_AVAILABLE: number;
			public static GL_R11F_G11F_B10F: number;
			public static GL_R16F: number;
			public static GL_R16I: number;
			public static GL_R16UI: number;
			public static GL_R32F: number;
			public static GL_R32I: number;
			public static GL_R32UI: number;
			public static GL_R8: number;
			public static GL_R8I: number;
			public static GL_R8UI: number;
			public static GL_R8_SNORM: number;
			public static GL_RASTERIZER_DISCARD: number;
			public static GL_READ_BUFFER: number;
			public static GL_READ_FRAMEBUFFER: number;
			public static GL_READ_FRAMEBUFFER_BINDING: number;
			public static GL_RED: number;
			public static GL_RED_INTEGER: number;
			public static GL_RENDERBUFFER_SAMPLES: number;
			public static GL_RG: number;
			public static GL_RG16F: number;
			public static GL_RG16I: number;
			public static GL_RG16UI: number;
			public static GL_RG32F: number;
			public static GL_RG32I: number;
			public static GL_RG32UI: number;
			public static GL_RG8: number;
			public static GL_RG8I: number;
			public static GL_RG8UI: number;
			public static GL_RG8_SNORM: number;
			public static GL_RGB10_A2: number;
			public static GL_RGB10_A2UI: number;
			public static GL_RGB16F: number;
			public static GL_RGB16I: number;
			public static GL_RGB16UI: number;
			public static GL_RGB32F: number;
			public static GL_RGB32I: number;
			public static GL_RGB32UI: number;
			public static GL_RGB8: number;
			public static GL_RGB8I: number;
			public static GL_RGB8UI: number;
			public static GL_RGB8_SNORM: number;
			public static GL_RGB9_E5: number;
			public static GL_RGBA16F: number;
			public static GL_RGBA16I: number;
			public static GL_RGBA16UI: number;
			public static GL_RGBA32F: number;
			public static GL_RGBA32I: number;
			public static GL_RGBA32UI: number;
			public static GL_RGBA8: number;
			public static GL_RGBA8I: number;
			public static GL_RGBA8UI: number;
			public static GL_RGBA8_SNORM: number;
			public static GL_RGBA_INTEGER: number;
			public static GL_RGB_INTEGER: number;
			public static GL_RG_INTEGER: number;
			public static GL_SAMPLER_2D_ARRAY: number;
			public static GL_SAMPLER_2D_ARRAY_SHADOW: number;
			public static GL_SAMPLER_2D_SHADOW: number;
			public static GL_SAMPLER_3D: number;
			public static GL_SAMPLER_BINDING: number;
			public static GL_SAMPLER_CUBE_SHADOW: number;
			public static GL_SEPARATE_ATTRIBS: number;
			public static GL_SIGNALED: number;
			public static GL_SIGNED_NORMALIZED: number;
			public static GL_SRGB: number;
			public static GL_SRGB8: number;
			public static GL_SRGB8_ALPHA8: number;
			public static GL_STATIC_COPY: number;
			public static GL_STATIC_READ: number;
			public static GL_STENCIL: number;
			public static GL_STREAM_COPY: number;
			public static GL_STREAM_READ: number;
			public static GL_SYNC_CONDITION: number;
			public static GL_SYNC_FENCE: number;
			public static GL_SYNC_FLAGS: number;
			public static GL_SYNC_FLUSH_COMMANDS_BIT: number;
			public static GL_SYNC_GPU_COMMANDS_COMPLETE: number;
			public static GL_SYNC_STATUS: number;
			public static GL_TEXTURE_2D_ARRAY: number;
			public static GL_TEXTURE_3D: number;
			public static GL_TEXTURE_BASE_LEVEL: number;
			public static GL_TEXTURE_BINDING_2D_ARRAY: number;
			public static GL_TEXTURE_BINDING_3D: number;
			public static GL_TEXTURE_COMPARE_FUNC: number;
			public static GL_TEXTURE_COMPARE_MODE: number;
			public static GL_TEXTURE_IMMUTABLE_FORMAT: number;
			public static GL_TEXTURE_IMMUTABLE_LEVELS: number;
			public static GL_TEXTURE_MAX_LEVEL: number;
			public static GL_TEXTURE_MAX_LOD: number;
			public static GL_TEXTURE_MIN_LOD: number;
			public static GL_TEXTURE_SWIZZLE_A: number;
			public static GL_TEXTURE_SWIZZLE_B: number;
			public static GL_TEXTURE_SWIZZLE_G: number;
			public static GL_TEXTURE_SWIZZLE_R: number;
			public static GL_TEXTURE_WRAP_R: number;
			public static GL_TIMEOUT_EXPIRED: number;
			public static GL_TIMEOUT_IGNORED: number;
			public static GL_TRANSFORM_FEEDBACK: number;
			public static GL_TRANSFORM_FEEDBACK_ACTIVE: number;
			public static GL_TRANSFORM_FEEDBACK_BINDING: number;
			public static GL_TRANSFORM_FEEDBACK_BUFFER: number;
			public static GL_TRANSFORM_FEEDBACK_BUFFER_BINDING: number;
			public static GL_TRANSFORM_FEEDBACK_BUFFER_MODE: number;
			public static GL_TRANSFORM_FEEDBACK_BUFFER_SIZE: number;
			public static GL_TRANSFORM_FEEDBACK_BUFFER_START: number;
			public static GL_TRANSFORM_FEEDBACK_PAUSED: number;
			public static GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN: number;
			public static GL_TRANSFORM_FEEDBACK_VARYINGS: number;
			public static GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH: number;
			public static GL_UNIFORM_ARRAY_STRIDE: number;
			public static GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS: number;
			public static GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES: number;
			public static GL_UNIFORM_BLOCK_BINDING: number;
			public static GL_UNIFORM_BLOCK_DATA_SIZE: number;
			public static GL_UNIFORM_BLOCK_INDEX: number;
			public static GL_UNIFORM_BLOCK_NAME_LENGTH: number;
			public static GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER: number;
			public static GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER: number;
			public static GL_UNIFORM_BUFFER: number;
			public static GL_UNIFORM_BUFFER_BINDING: number;
			public static GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT: number;
			public static GL_UNIFORM_BUFFER_SIZE: number;
			public static GL_UNIFORM_BUFFER_START: number;
			public static GL_UNIFORM_IS_ROW_MAJOR: number;
			public static GL_UNIFORM_MATRIX_STRIDE: number;
			public static GL_UNIFORM_NAME_LENGTH: number;
			public static GL_UNIFORM_OFFSET: number;
			public static GL_UNIFORM_SIZE: number;
			public static GL_UNIFORM_TYPE: number;
			public static GL_UNPACK_IMAGE_HEIGHT: number;
			public static GL_UNPACK_ROW_LENGTH: number;
			public static GL_UNPACK_SKIP_IMAGES: number;
			public static GL_UNPACK_SKIP_PIXELS: number;
			public static GL_UNPACK_SKIP_ROWS: number;
			public static GL_UNSIGNALED: number;
			public static GL_UNSIGNED_INT_10F_11F_11F_REV: number;
			public static GL_UNSIGNED_INT_24_8: number;
			public static GL_UNSIGNED_INT_2_10_10_10_REV: number;
			public static GL_UNSIGNED_INT_5_9_9_9_REV: number;
			public static GL_UNSIGNED_INT_SAMPLER_2D: number;
			public static GL_UNSIGNED_INT_SAMPLER_2D_ARRAY: number;
			public static GL_UNSIGNED_INT_SAMPLER_3D: number;
			public static GL_UNSIGNED_INT_SAMPLER_CUBE: number;
			public static GL_UNSIGNED_INT_VEC2: number;
			public static GL_UNSIGNED_INT_VEC3: number;
			public static GL_UNSIGNED_INT_VEC4: number;
			public static GL_UNSIGNED_NORMALIZED: number;
			public static GL_VERTEX_ARRAY_BINDING: number;
			public static GL_VERTEX_ATTRIB_ARRAY_DIVISOR: number;
			public static GL_VERTEX_ATTRIB_ARRAY_INTEGER: number;
			public static GL_WAIT_FAILED: number;
		}
	}
}
