/// <reference path="./_helpers.d.ts" />
/// <reference path="./java.io.InputStream.d.ts" />
/// <reference path="./java.io.Reader.d.ts" />
/// <reference path="./java.lang.String.d.ts" />
/// <reference path="./java.math.BigDecimal.d.ts" />
/// <reference path="./java.net.URL.d.ts" />
/// <reference path="./java.sql.Array.d.ts" />
/// <reference path="./java.sql.Blob.d.ts" />
/// <reference path="./java.sql.Clob.d.ts" />
/// <reference path="./java.sql.Date.d.ts" />
/// <reference path="./java.sql.NClob.d.ts" />
/// <reference path="./java.sql.Ref.d.ts" />
/// <reference path="./java.sql.RowId.d.ts" />
/// <reference path="./java.sql.SQLData.d.ts" />
/// <reference path="./java.sql.SQLXML.d.ts" />
/// <reference path="./java.sql.Struct.d.ts" />
/// <reference path="./java.sql.Time.d.ts" />
/// <reference path="./java.sql.Timestamp.d.ts" />

declare module java {
	export module sql {
		export class SQLOutput {
			public writeString(param0: string): void;
			public writeBoolean(param0: boolean): void;
			public writeByte(param0: number): void;
			public writeShort(param0: number): void;
			public writeInt(param0: number): void;
			public writeLong(param0: number): void;
			public writeFloat(param0: number): void;
			public writeDouble(param0: number): void;
			public writeBigDecimal(param0: java.math.BigDecimal): void;
			public writeBytes(param0: native.Array<number>): void;
			public writeDate(param0: java.sql.Date): void;
			public writeTime(param0: java.sql.Time): void;
			public writeTimestamp(param0: java.sql.Timestamp): void;
			public writeCharacterStream(param0: java.io.Reader): void;
			public writeAsciiStream(param0: java.io.InputStream): void;
			public writeBinaryStream(param0: java.io.InputStream): void;
			public writeObject(param0: java.sql.SQLData): void;
			public writeRef(param0: java.sql.Ref): void;
			public writeBlob(param0: java.sql.Blob): void;
			public writeClob(param0: java.sql.Clob): void;
			public writeStruct(param0: java.sql.Struct): void;
			public writeArray(param0: java.sql.Array): void;
			public writeURL(param0: java.net.URL): void;
			public writeNString(param0: string): void;
			public writeNClob(param0: java.sql.NClob): void;
			public writeRowId(param0: java.sql.RowId): void;
			public writeSQLXML(param0: java.sql.SQLXML): void;
		}
	}
}
