/// <reference path="./_helpers.d.ts" />
/// <reference path="./java.nio.Buffer.d.ts" />
/// <reference path="./java.nio.FloatBuffer.d.ts" />
/// <reference path="./java.nio.IntBuffer.d.ts" />

declare module javax {
	export module microedition {
		export module khronos {
			export module opengles {
				export class GL10 {
					public glActiveTexture(param0: number): void;
					public glAlphaFunc(param0: number, param1: number): void;
					public glAlphaFuncx(param0: number, param1: number): void;
					public glBindTexture(param0: number, param1: number): void;
					public glBlendFunc(param0: number, param1: number): void;
					public glClear(param0: number): void;
					public glClearColor(param0: number, param1: number, param2: number, param3: number): void;
					public glClearColorx(param0: number, param1: number, param2: number, param3: number): void;
					public glClearDepthf(param0: number): void;
					public glClearDepthx(param0: number): void;
					public glClearStencil(param0: number): void;
					public glClientActiveTexture(param0: number): void;
					public glColor4f(param0: number, param1: number, param2: number, param3: number): void;
					public glColor4x(param0: number, param1: number, param2: number, param3: number): void;
					public glColorMask(param0: boolean, param1: boolean, param2: boolean, param3: boolean): void;
					public glColorPointer(param0: number, param1: number, param2: number, param3: java.nio.Buffer): void;
					public glCompressedTexImage2D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: java.nio.Buffer): void;
					public glCompressedTexSubImage2D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: java.nio.Buffer): void;
					public glCopyTexImage2D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number): void;
					public glCopyTexSubImage2D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number): void;
					public glCullFace(param0: number): void;
					public glDeleteTextures(param0: number, param1: native.Array<number>, param2: number): void;
					public glDeleteTextures(param0: number, param1: java.nio.IntBuffer): void;
					public glDepthFunc(param0: number): void;
					public glDepthMask(param0: boolean): void;
					public glDepthRangef(param0: number, param1: number): void;
					public glDepthRangex(param0: number, param1: number): void;
					public glDisable(param0: number): void;
					public glDisableClientState(param0: number): void;
					public glDrawArrays(param0: number, param1: number, param2: number): void;
					public glDrawElements(param0: number, param1: number, param2: number, param3: java.nio.Buffer): void;
					public glEnable(param0: number): void;
					public glEnableClientState(param0: number): void;
					public glFinish(): void;
					public glFlush(): void;
					public glFogf(param0: number, param1: number): void;
					public glFogfv(param0: number, param1: native.Array<number>, param2: number): void;
					public glFogfv(param0: number, param1: java.nio.FloatBuffer): void;
					public glFogx(param0: number, param1: number): void;
					public glFogxv(param0: number, param1: native.Array<number>, param2: number): void;
					public glFogxv(param0: number, param1: java.nio.IntBuffer): void;
					public glFrontFace(param0: number): void;
					public glFrustumf(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number): void;
					public glFrustumx(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number): void;
					public glGenTextures(param0: number, param1: native.Array<number>, param2: number): void;
					public glGenTextures(param0: number, param1: java.nio.IntBuffer): void;
					public glGetError(): number;
					public glGetIntegerv(param0: number, param1: native.Array<number>, param2: number): void;
					public glGetIntegerv(param0: number, param1: java.nio.IntBuffer): void;
					public glGetString(param0: number): string;
					public glHint(param0: number, param1: number): void;
					public glLightModelf(param0: number, param1: number): void;
					public glLightModelfv(param0: number, param1: native.Array<number>, param2: number): void;
					public glLightModelfv(param0: number, param1: java.nio.FloatBuffer): void;
					public glLightModelx(param0: number, param1: number): void;
					public glLightModelxv(param0: number, param1: native.Array<number>, param2: number): void;
					public glLightModelxv(param0: number, param1: java.nio.IntBuffer): void;
					public glLightf(param0: number, param1: number, param2: number): void;
					public glLightfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
					public glLightfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
					public glLightx(param0: number, param1: number, param2: number): void;
					public glLightxv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
					public glLightxv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
					public glLineWidth(param0: number): void;
					public glLineWidthx(param0: number): void;
					public glLoadIdentity(): void;
					public glLoadMatrixf(param0: native.Array<number>, param1: number): void;
					public glLoadMatrixf(param0: java.nio.FloatBuffer): void;
					public glLoadMatrixx(param0: native.Array<number>, param1: number): void;
					public glLoadMatrixx(param0: java.nio.IntBuffer): void;
					public glLogicOp(param0: number): void;
					public glMaterialf(param0: number, param1: number, param2: number): void;
					public glMaterialfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
					public glMaterialfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
					public glMaterialx(param0: number, param1: number, param2: number): void;
					public glMaterialxv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
					public glMaterialxv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
					public glMatrixMode(param0: number): void;
					public glMultMatrixf(param0: native.Array<number>, param1: number): void;
					public glMultMatrixf(param0: java.nio.FloatBuffer): void;
					public glMultMatrixx(param0: native.Array<number>, param1: number): void;
					public glMultMatrixx(param0: java.nio.IntBuffer): void;
					public glMultiTexCoord4f(param0: number, param1: number, param2: number, param3: number, param4: number): void;
					public glMultiTexCoord4x(param0: number, param1: number, param2: number, param3: number, param4: number): void;
					public glNormal3f(param0: number, param1: number, param2: number): void;
					public glNormal3x(param0: number, param1: number, param2: number): void;
					public glNormalPointer(param0: number, param1: number, param2: java.nio.Buffer): void;
					public glOrthof(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number): void;
					public glOrthox(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number): void;
					public glPixelStorei(param0: number, param1: number): void;
					public glPointSize(param0: number): void;
					public glPointSizex(param0: number): void;
					public glPolygonOffset(param0: number, param1: number): void;
					public glPolygonOffsetx(param0: number, param1: number): void;
					public glPopMatrix(): void;
					public glPushMatrix(): void;
					public glReadPixels(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: java.nio.Buffer): void;
					public glRotatef(param0: number, param1: number, param2: number, param3: number): void;
					public glRotatex(param0: number, param1: number, param2: number, param3: number): void;
					public glSampleCoverage(param0: number, param1: boolean): void;
					public glSampleCoveragex(param0: number, param1: boolean): void;
					public glScalef(param0: number, param1: number, param2: number): void;
					public glScalex(param0: number, param1: number, param2: number): void;
					public glScissor(param0: number, param1: number, param2: number, param3: number): void;
					public glShadeModel(param0: number): void;
					public glStencilFunc(param0: number, param1: number, param2: number): void;
					public glStencilMask(param0: number): void;
					public glStencilOp(param0: number, param1: number, param2: number): void;
					public glTexCoordPointer(param0: number, param1: number, param2: number, param3: java.nio.Buffer): void;
					public glTexEnvf(param0: number, param1: number, param2: number): void;
					public glTexEnvfv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
					public glTexEnvfv(param0: number, param1: number, param2: java.nio.FloatBuffer): void;
					public glTexEnvx(param0: number, param1: number, param2: number): void;
					public glTexEnvxv(param0: number, param1: number, param2: native.Array<number>, param3: number): void;
					public glTexEnvxv(param0: number, param1: number, param2: java.nio.IntBuffer): void;
					public glTexImage2D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: java.nio.Buffer): void;
					public glTexParameterf(param0: number, param1: number, param2: number): void;
					public glTexParameterx(param0: number, param1: number, param2: number): void;
					public glTexSubImage2D(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: number, param8: java.nio.Buffer): void;
					public glTranslatef(param0: number, param1: number, param2: number): void;
					public glTranslatex(param0: number, param1: number, param2: number): void;
					public glVertexPointer(param0: number, param1: number, param2: number, param3: java.nio.Buffer): void;
					public glViewport(param0: number, param1: number, param2: number, param3: number): void;
					public static GL_ADD: number;
					public static GL_ALIASED_LINE_WIDTH_RANGE: number;
					public static GL_ALIASED_POINT_SIZE_RANGE: number;
					public static GL_ALPHA: number;
					public static GL_ALPHA_BITS: number;
					public static GL_ALPHA_TEST: number;
					public static GL_ALWAYS: number;
					public static GL_AMBIENT: number;
					public static GL_AMBIENT_AND_DIFFUSE: number;
					public static GL_AND: number;
					public static GL_AND_INVERTED: number;
					public static GL_AND_REVERSE: number;
					public static GL_BACK: number;
					public static GL_BLEND: number;
					public static GL_BLUE_BITS: number;
					public static GL_BYTE: number;
					public static GL_CCW: number;
					public static GL_CLAMP_TO_EDGE: number;
					public static GL_CLEAR: number;
					public static GL_COLOR_ARRAY: number;
					public static GL_COLOR_BUFFER_BIT: number;
					public static GL_COLOR_LOGIC_OP: number;
					public static GL_COLOR_MATERIAL: number;
					public static GL_COMPRESSED_TEXTURE_FORMATS: number;
					public static GL_CONSTANT_ATTENUATION: number;
					public static GL_COPY: number;
					public static GL_COPY_INVERTED: number;
					public static GL_CULL_FACE: number;
					public static GL_CW: number;
					public static GL_DECAL: number;
					public static GL_DECR: number;
					public static GL_DEPTH_BITS: number;
					public static GL_DEPTH_BUFFER_BIT: number;
					public static GL_DEPTH_TEST: number;
					public static GL_DIFFUSE: number;
					public static GL_DITHER: number;
					public static GL_DONT_CARE: number;
					public static GL_DST_ALPHA: number;
					public static GL_DST_COLOR: number;
					public static GL_EMISSION: number;
					public static GL_EQUAL: number;
					public static GL_EQUIV: number;
					public static GL_EXP: number;
					public static GL_EXP2: number;
					public static GL_EXTENSIONS: number;
					public static GL_FALSE: number;
					public static GL_FASTEST: number;
					public static GL_FIXED: number;
					public static GL_FLAT: number;
					public static GL_FLOAT: number;
					public static GL_FOG: number;
					public static GL_FOG_COLOR: number;
					public static GL_FOG_DENSITY: number;
					public static GL_FOG_END: number;
					public static GL_FOG_HINT: number;
					public static GL_FOG_MODE: number;
					public static GL_FOG_START: number;
					public static GL_FRONT: number;
					public static GL_FRONT_AND_BACK: number;
					public static GL_GEQUAL: number;
					public static GL_GREATER: number;
					public static GL_GREEN_BITS: number;
					public static GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES: number;
					public static GL_IMPLEMENTATION_COLOR_READ_TYPE_OES: number;
					public static GL_INCR: number;
					public static GL_INVALID_ENUM: number;
					public static GL_INVALID_OPERATION: number;
					public static GL_INVALID_VALUE: number;
					public static GL_INVERT: number;
					public static GL_KEEP: number;
					public static GL_LEQUAL: number;
					public static GL_LESS: number;
					public static GL_LIGHT0: number;
					public static GL_LIGHT1: number;
					public static GL_LIGHT2: number;
					public static GL_LIGHT3: number;
					public static GL_LIGHT4: number;
					public static GL_LIGHT5: number;
					public static GL_LIGHT6: number;
					public static GL_LIGHT7: number;
					public static GL_LIGHTING: number;
					public static GL_LIGHT_MODEL_AMBIENT: number;
					public static GL_LIGHT_MODEL_TWO_SIDE: number;
					public static GL_LINEAR: number;
					public static GL_LINEAR_ATTENUATION: number;
					public static GL_LINEAR_MIPMAP_LINEAR: number;
					public static GL_LINEAR_MIPMAP_NEAREST: number;
					public static GL_LINES: number;
					public static GL_LINE_LOOP: number;
					public static GL_LINE_SMOOTH: number;
					public static GL_LINE_SMOOTH_HINT: number;
					public static GL_LINE_STRIP: number;
					public static GL_LUMINANCE: number;
					public static GL_LUMINANCE_ALPHA: number;
					public static GL_MAX_ELEMENTS_INDICES: number;
					public static GL_MAX_ELEMENTS_VERTICES: number;
					public static GL_MAX_LIGHTS: number;
					public static GL_MAX_MODELVIEW_STACK_DEPTH: number;
					public static GL_MAX_PROJECTION_STACK_DEPTH: number;
					public static GL_MAX_TEXTURE_SIZE: number;
					public static GL_MAX_TEXTURE_STACK_DEPTH: number;
					public static GL_MAX_TEXTURE_UNITS: number;
					public static GL_MAX_VIEWPORT_DIMS: number;
					public static GL_MODELVIEW: number;
					public static GL_MODULATE: number;
					public static GL_MULTISAMPLE: number;
					public static GL_NAND: number;
					public static GL_NEAREST: number;
					public static GL_NEAREST_MIPMAP_LINEAR: number;
					public static GL_NEAREST_MIPMAP_NEAREST: number;
					public static GL_NEVER: number;
					public static GL_NICEST: number;
					public static GL_NOOP: number;
					public static GL_NOR: number;
					public static GL_NORMALIZE: number;
					public static GL_NORMAL_ARRAY: number;
					public static GL_NOTEQUAL: number;
					public static GL_NO_ERROR: number;
					public static GL_NUM_COMPRESSED_TEXTURE_FORMATS: number;
					public static GL_ONE: number;
					public static GL_ONE_MINUS_DST_ALPHA: number;
					public static GL_ONE_MINUS_DST_COLOR: number;
					public static GL_ONE_MINUS_SRC_ALPHA: number;
					public static GL_ONE_MINUS_SRC_COLOR: number;
					public static GL_OR: number;
					public static GL_OR_INVERTED: number;
					public static GL_OR_REVERSE: number;
					public static GL_OUT_OF_MEMORY: number;
					public static GL_PACK_ALIGNMENT: number;
					public static GL_PALETTE4_R5_G6_B5_OES: number;
					public static GL_PALETTE4_RGB5_A1_OES: number;
					public static GL_PALETTE4_RGB8_OES: number;
					public static GL_PALETTE4_RGBA4_OES: number;
					public static GL_PALETTE4_RGBA8_OES: number;
					public static GL_PALETTE8_R5_G6_B5_OES: number;
					public static GL_PALETTE8_RGB5_A1_OES: number;
					public static GL_PALETTE8_RGB8_OES: number;
					public static GL_PALETTE8_RGBA4_OES: number;
					public static GL_PALETTE8_RGBA8_OES: number;
					public static GL_PERSPECTIVE_CORRECTION_HINT: number;
					public static GL_POINTS: number;
					public static GL_POINT_FADE_THRESHOLD_SIZE: number;
					public static GL_POINT_SIZE: number;
					public static GL_POINT_SMOOTH: number;
					public static GL_POINT_SMOOTH_HINT: number;
					public static GL_POLYGON_OFFSET_FILL: number;
					public static GL_POLYGON_SMOOTH_HINT: number;
					public static GL_POSITION: number;
					public static GL_PROJECTION: number;
					public static GL_QUADRATIC_ATTENUATION: number;
					public static GL_RED_BITS: number;
					public static GL_RENDERER: number;
					public static GL_REPEAT: number;
					public static GL_REPLACE: number;
					public static GL_RESCALE_NORMAL: number;
					public static GL_RGB: number;
					public static GL_RGBA: number;
					public static GL_SAMPLE_ALPHA_TO_COVERAGE: number;
					public static GL_SAMPLE_ALPHA_TO_ONE: number;
					public static GL_SAMPLE_COVERAGE: number;
					public static GL_SCISSOR_TEST: number;
					public static GL_SET: number;
					public static GL_SHININESS: number;
					public static GL_SHORT: number;
					public static GL_SMOOTH: number;
					public static GL_SMOOTH_LINE_WIDTH_RANGE: number;
					public static GL_SMOOTH_POINT_SIZE_RANGE: number;
					public static GL_SPECULAR: number;
					public static GL_SPOT_CUTOFF: number;
					public static GL_SPOT_DIRECTION: number;
					public static GL_SPOT_EXPONENT: number;
					public static GL_SRC_ALPHA: number;
					public static GL_SRC_ALPHA_SATURATE: number;
					public static GL_SRC_COLOR: number;
					public static GL_STACK_OVERFLOW: number;
					public static GL_STACK_UNDERFLOW: number;
					public static GL_STENCIL_BITS: number;
					public static GL_STENCIL_BUFFER_BIT: number;
					public static GL_STENCIL_TEST: number;
					public static GL_SUBPIXEL_BITS: number;
					public static GL_TEXTURE: number;
					public static GL_TEXTURE0: number;
					public static GL_TEXTURE1: number;
					public static GL_TEXTURE10: number;
					public static GL_TEXTURE11: number;
					public static GL_TEXTURE12: number;
					public static GL_TEXTURE13: number;
					public static GL_TEXTURE14: number;
					public static GL_TEXTURE15: number;
					public static GL_TEXTURE16: number;
					public static GL_TEXTURE17: number;
					public static GL_TEXTURE18: number;
					public static GL_TEXTURE19: number;
					public static GL_TEXTURE2: number;
					public static GL_TEXTURE20: number;
					public static GL_TEXTURE21: number;
					public static GL_TEXTURE22: number;
					public static GL_TEXTURE23: number;
					public static GL_TEXTURE24: number;
					public static GL_TEXTURE25: number;
					public static GL_TEXTURE26: number;
					public static GL_TEXTURE27: number;
					public static GL_TEXTURE28: number;
					public static GL_TEXTURE29: number;
					public static GL_TEXTURE3: number;
					public static GL_TEXTURE30: number;
					public static GL_TEXTURE31: number;
					public static GL_TEXTURE4: number;
					public static GL_TEXTURE5: number;
					public static GL_TEXTURE6: number;
					public static GL_TEXTURE7: number;
					public static GL_TEXTURE8: number;
					public static GL_TEXTURE9: number;
					public static GL_TEXTURE_2D: number;
					public static GL_TEXTURE_COORD_ARRAY: number;
					public static GL_TEXTURE_ENV: number;
					public static GL_TEXTURE_ENV_COLOR: number;
					public static GL_TEXTURE_ENV_MODE: number;
					public static GL_TEXTURE_MAG_FILTER: number;
					public static GL_TEXTURE_MIN_FILTER: number;
					public static GL_TEXTURE_WRAP_S: number;
					public static GL_TEXTURE_WRAP_T: number;
					public static GL_TRIANGLES: number;
					public static GL_TRIANGLE_FAN: number;
					public static GL_TRIANGLE_STRIP: number;
					public static GL_TRUE: number;
					public static GL_UNPACK_ALIGNMENT: number;
					public static GL_UNSIGNED_BYTE: number;
					public static GL_UNSIGNED_SHORT: number;
					public static GL_UNSIGNED_SHORT_4_4_4_4: number;
					public static GL_UNSIGNED_SHORT_5_5_5_1: number;
					public static GL_UNSIGNED_SHORT_5_6_5: number;
					public static GL_VENDOR: number;
					public static GL_VERSION: number;
					public static GL_VERTEX_ARRAY: number;
					public static GL_XOR: number;
					public static GL_ZERO: number;
				}
			}
		}
	}
}
